NilFoundation/nil

- nil/client/rpc/client.go
Introduced a dedicated `rpc.CallError` type for RPC errors to detect them using `errors.As(...)` call
> Declared `rpc.CallError` type

- go.mod
- go.sum
- nil/services/synccommittee/Makefile.inc
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/batches/blob/builder.go
- nil/services/synccommittee/core/batches/blob/builder_test.go
- nil/services/synccommittee/core/batches/commiter.go
- nil/services/synccommittee/core/batches/encode/header.go
- nil/services/synccommittee/core/batches/encode/v1/encoder.go
- nil/services/synccommittee/core/batches/encode/v1/encoder_test.go
- nil/services/synccommittee/core/batches/encode/v1/serialization.go
- nil/services/synccommittee/core/batches/encode/v1/zstd.go
- nil/services/synccommittee/internal/types/block_batch.go
- nil/services/synccommittee/internal/types/blocks.go
- nil/services/synccommittee/internal/types/proto/blob_transaction.proto
- nix/nil.nix
Transition of https://github.com/NilFoundation/nil-old/pull/1564
Added initial support for committing transaction batch to L1
Logic is:
- pick batch from aggregator
- serialize it to protobuf
- compress with zstd
- pack to blobs (according to spec each u256 element is 254 bits of payload and 2 bits of padding)
- commit with blob tx to L1 (TBD, waiting for L1 contract update)
Batch encoder is isolated into separate interface in order to be able to do batch serialization/encoding verisioning
> sc: add blob send to L1

- nil/internal/execution/fee.go
Decimal's Pow function is not thread-safe, so we need to lock it manually. This is a workaround, we need to remove the lock after Decimal will be fixed or find a better solution.
https://github.com/shopspring/decimal/issues/368
> Fix race condition in fee calculation

- flake.nix
- nix/tests-heavy.txt
- nix/tests-ibft.txt
Let's hope that they will execute fine with lower parallelism.
> Move flaky tests from the "nil" group

- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/scheduler.go
- nil/internal/collate/testaide.go
- nil/internal/collate/validator.go
- nil/internal/execution/block_generator.go
- nil/services/txnpool/txnpool.go
- nil/services/txnpool/txnpoolcfg.go
This PR depends on the proposer refactoring: https://github.com/NilFoundation/nil/pull/66
When the proposal was used synchronously, it used to carry the list of txns to be removed from the pool.
This list consisted of all the committed txns + all failed (duplicates and those that failed external verifications).
Validators can remove committed txns from their pools.
Failed txns (duplicates and unverified) should be removed only from the proposer's pool (they might not even exist in other validators' pools). And it can be done before the consensus because they are invalid regardless.
1. Removed `RemoveFromPool` from the proposal.
2. Added `Discard` to the pool interface and implemented.
3. Used the added method to discard failed txns from the proposer's pool.
4. Switched `OnCommitted` to …
> Remove failed txns from proposal

- nil/tests/nil_load_generator_service/nil_load_generator_test.go
Occasionally, the balances turn out to be zero, and the Greater() check below fails later.
This is an attempt to catch this condition earlier, with better logging.
This won't help in all cases:
```
> --- FAIL: TestNilLoadGeneratorRpcRpc (23.36s)
>     --- FAIL: TestNilLoadGeneratorRpcRpc/TestSmartAccountBalanceModification (23.27s)
>         nil_load_generator_test.go:87:
>                 Error Trace:    /build/source/nil/tests/nil_load_generator_service/nil_load_generator_test.go:87
>               Error:          "9998724480000000" is not greater than "9998724480000000"
>              Test:           TestNilLoadGeneratorRpcRpc/TestSmartAccountBalanceModification
> FAIL
```
(happened [here](https://github.com/NilFoundation/nil/actions/runs/13080458637/job/36502620050?pr=76)).
> [loadgen-test] Check for positive balances.

- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/execution/block_generator.go
- nil/services/nilservice/service.go
In case of several validators it should be able to be in-sync. So we need to create syncer even for active shards.
Closes #109
> make syncer permanent

- explorer_frontend/src/features/contracts/models/base.ts
This pull request includes a change to the `explorer_frontend/src/features/contracts/models/base.ts` file to correct the method used for retrieving transaction receipts.
* [`explorer_frontend/src/features/contracts/models/base.ts`](diffhunk://#diff-db44f990ebdaec3245f2c2986a410f1e58b87bd793576613d4c0c2a824f49cfeL274-R274): Changed the method from `getMessageReceiptByHash` to `getTransactionReceiptByHash` to accurately retrieve transaction receipts.
It is incorrect method name, currently we have `getTransactionReceiptByHash` in niljs.
> Rename getMessageReceiptByHash to getTransactionReceiptByHash

- docs/docusaurus.config.js
- docs/nil/block-explorer/usage.mdx
- docs/nil/cookbook/faucet-service/use-faucet-service.mdx
- docs/nil/cookbook/index.mdx
- docs/nil/guides/app-migration.mdx
- docs/nil/migration-guides/december-0412-2024-release.mdx
- docs/nil/migration-guides/november-0611-2024-release.mdx
- docs/nil/migration-guides/november-2011-2024-release.mdx
- docs/nil/migration-guides/october-1510-2024-release.mdx
- docs/nil/migration-guides/september-2024-release.mdx
- docs/nil/prerequisites.mdx
- docs/nil/smart-contracts/func-modifiers.mdx
- docs/nil/specification/principles.mdx
This diff fixes more non-working links and removes the theme switcher.
> [docs] links fixes and switcher fix

- explorer_frontend/src/features/account-connector/init.ts
- explorer_frontend/src/features/contracts/components/Deploy/AssignTab.tsx
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/base.ts
Changed AssignTab explicitly to disallow duplication of contracts and clearing of address on modal close. 
- Changed assign tab to not show addresses persisting from previous interaction. Upon close of modal, you have a clear input tab. 
- This PR also adds logic to not allow duplication of contracts which is, once you have deployed a contract, you cannot use the same address to assign it again when the deployed contract still exists in the sandbox.
> Explorer bugs

- nil/cmd/exporter/internal/fetch_block_test.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/consensus/ibft/signer.go
- nil/internal/consensus/ibft/validators.go
- nil/internal/consensus/ibft/verifier.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/services/synccommittee/core/service_test.go
- nil/services/txnpool/txnpool_test.go
- nil/tests/consensus/consensus_test.go
- nil/tests/rpc_suite.go
- nil/tests/sharded_suite.go
This patch implements several fixes to support shard consensus for several shards.
Basically I added a new test. But some other tests are also affected to make it more consistent with general test approaches.
> test: run consensus with several validators

- nil/internal/execution/state.go
`NUMBER` opcode should return number of the current block, not the previous one.
> Fix evm's NUMBER opcode

- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/base.ts
- explorer_frontend/src/features/logs/init.tsx
This diff makes contract registration in cometa service optional. This improves user flow by decreasing amount of potential pain points. It contract was deployed but not registered in cometa - user is going to see warning in console.
* Added `registerContractInCometaFx` to the list of imported effects and included it in the `sample` function to register contracts upon successful deployment. (`explorer_frontend/src/features/contracts/init.ts`, [[1]](diffhunk://#diff-0520c98b0b5c9b833307795bdd3996a1399307502de66eea027793ec52a663baR45) [[2]](diffhunk://#diff-0520c98b0b5c9b833307795bdd3996a1399307502de66eea027793ec52a663baR576-R599)
* Removed `cometaService` and `solidityVersion` from the `sample` function parameters and the `deploySmartContractFx` effect. …
> Make cometa contract register optional

- explorer_frontend/src/features/contracts/components/Deploy/DeployContractModal.tsx
- explorer_frontend/src/features/contracts/components/Deploy/ImportContractTab.tsx
This PR introduces renaming of "Assign" Tab -> "Import Contract"  and a small hint under the address input to tell the user to insert the address of the already deployed smart contract(with its name).
> Change of Assign tab to Import Contract tab

- nil/cmd/nild/devnet.go
This was the reason for validators and RPC nodes fighting for the same ports.
> Fix validator RPC port assignment.

- nil/internal/collate/scheduler.go
It could cause a race condition.
It could cause a race condition.
Imagine following case our validator started RunSequence but for some
reasons syncer got block before InsertProposal.
In that case we need to interrupt consensus sequence. And we do that
in defer (we call context cancel).
But seems some processes don't happen immediately. And we need to wait
for complete termination of RunSequence. Here we add two lines:
the first one cancels context (it will be called second time in defer but
seems it's safe in Go). And the second one just waits for some result from
RunSequence function. This delay should be quite quick.
> [consensus] don't start new round until previous one is not completely finished

- nil/contracts/solidity/tests/Counter.sol
- nil/contracts/solidity/tests/RequestResponseTest.sol
- nil/tests/async_await/async_await_test.go
This patch decrease a time that async_await test consumes from 90s to 25s. Here we reset contract values instead of recreate test server each time.
> [tests] improve async_await test speed

- nil/tests/economy/economy_test.go
All tests are independent. It allows us to run nil server only once for all tests. Also `CollatorTickPeriodMs` is decreased a bit.
> [tests] speedup economy test

- nil/internal/collate/proposer.go
- nil/internal/network/pubsub.go
Changed log level for two non-errors:
- message to self (trace)
- saved temporary fail receipt (info)
> [log] fix spammy message level

- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/config/config.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/testaide.go
It's not correct to rely on the latest block.
Main block can be committed earlier than current one that can lead to the case when we read data from a newer source.
We fixed almost the same issue before for `collectGasPrices` function because it affected consensus. This part can also affect it in some ways.
> [execution] use specific main shard hash from block generation

- nil/Makefile.inc
Some mocks are depends on generated ssz types. Let's add them to makefile.
Closes #112
> [build] fix mocks dependencies

- niljs/src/rpc/rpcClient.test.ts
- niljs/src/rpc/rpcClient.ts
- niljs/src/transport/HttpTransport.ts
- niljs/src/transport/types/IHttpTransportConfig.ts
- niljs/src/utils/rpc.ts
This pull request introduces several changes to enhance the handling of HTTP headers in the RPC client and transport layer. The most important changes include adding support for custom headers, validating headers, and updating the relevant tests.
Enhancements to HTTP headers handling:
* [`niljs/src/rpc/rpcClient.ts`](diffhunk://#diff-99c944131423541a8baddcc26ac57d0674b5baa283fdfc482382942501b60de8R4-R11): Introduced an optional `headers` parameter in the `RPCClientOptions` type and updated the `createRPCClient` function to include these headers in the HTTP transport configuration. Added a call to `isValidHttpHeaders` to validate the headers. [[1]](diffhunk://#diff-99c944131423541a8baddcc26ac57d0674b5baa283fdfc482382942501b60de8R4-R11) …
> Allow to pass custom headers to http-transport in niljs

- docs/nil/prerequisites.mdx
- docs/nil/scripts/cliRefGenerator.ts
- nix/nildocs.nix
This diff fixes two bugs in docs:
* CLI references generation. Right now, no refs are generated as part of CI because the Nix env cannot find the `nil` binary. The `nildocs` derivation is adjusted to have a path to the correct binary, and the binary is used in the ref generator.
* The remnants of the broken links introduced by the renaming of terms are also fixed.
> [docs] fixed CLI refs generation

- nil/services/cometa/service.go
- nil/services/faucet/service.go
- nil/services/nil_load_generator/service.go
- nil/services/nilservice/service.go
- nil/services/rpc/server.go
- nil/services/rpc/server_test.go
- nil/services/synccommittee/internal/rpc/task_listener.go
The `StartRpcServer` function now accepts an optional `started` channel to signal when the server is ready.
This allows tests or dependent services to wait for the server to start before proceeding.
Used in #114 [here](https://github.com/NilFoundation/nil/pull/114/files#diff-542761f02f1af7ddd793620cd7937512d98bd4c03272d5105be85d0418857b7fR68).
Also helped to get rid of tcp polling in SyncCommittee's tests [here](https://github.com/NilFoundation/nil/pull/114/files#diff-65c07945e59b0f995aecbbc1b34838a373453561b392bd9282c4145e6ebb653bL34) and [here](https://github.com/NilFoundation/nil/pull/114/files#diff-62d417a55fb50077c21a27d5093d9e94fa49308906eef45359c4e5672ef05e6dL101)
> Add `started` channel to `StartRpcServer` for synchronization

- .github/workflows/main.yml
- nix/overlay.nix
This PR adds `clijs` builds for macOS (x86_64 and ARM) via Nix.
The builds take a long time (about an hour) due to unconfigured caching in Nix. This will be addressed in a separate task. Builds are not marked required, so we consider this option acceptable for now. For the same reason, we are not adding other checks via Nix yet.
`install-nix-action` uses `max-jobs = auto` by default, which leads to test instability. Took a long time going through images and disabling tests until I got to the cause. The setting was changed to the standard `max-jobs = 1`.
Closes #65.
> [GH-65] Add clijs macOS CI build over nix

- Makefile
- nil/cmd/exporter/internal/clickhouse/clickhouse.go
- nil/common/sszx/Makefile.inc
- nil/common/sszx/map.go
- nil/common/sszx/ssz.go
- nil/internal/execution/state_accessor.go
- nil/internal/mpt/accessors.go
- nil/internal/mpt/mpt_test.go
- nil/internal/mpt/proof.go
- nil/internal/mpt/proof_test.go
- nil/internal/types/block.go
- nil/services/rpc/rawapi/api.go
- nil/services/rpc/rawapi/client.go
- nil/services/rpc/rawapi/client_test.go
- nil/services/rpc/rawapi/codec_test.go
- nil/services/rpc/rawapi/local_block.go
- nil/services/rpc/rawapi/node.go
- nil/services/rpc/rawapi/pb/conversion.go
- nil/services/rpc/rawapi/server_test.go
- nil/services/synccommittee/prover/tracer/tracer_mock_client_test.go
We need proofs for internal transactions in the proposal.
Since they come in batches in consecutive order, storing their proofs is possible via sparse mpts (containing only the desired paths).
An mpt can be stored as a key-value map. Since serialization requires order which is not provided by the standard map, a wrapper is introduced.
The rest of the PR is a light refactoring of mpt and proposal.
1. Map wrapper in `ssz` package.
2. Simplified mpt ctors.
3. Renamed ssz package to sszx, because it conflicts with fastssz in generated code (in my future code, not here).
> [mpt] Refactoring to introduce SSZ for sparse tries

- nil/services/synccommittee/prover/proto/traces.proto
- nil/services/synccommittee/prover/tracer/keccak_tracer.go
- nil/services/synccommittee/prover/tracer/keccak_tracer_test.go
- nil/services/synccommittee/prover/tracer/memory_op_tracer.go
- nil/services/synccommittee/prover/tracer/serialization.go
- nil/services/synccommittee/prover/tracer/state_db.go
- nil/services/synccommittee/prover/tracer/tracer.go
- nil/services/synccommittee/prover/tracer/tracer_mock_client_test.go
- nil/services/synccommittee/prover/tracer/types.go
Our proof system has independent circuit for proving KECCAK256 opcode execution. Inputs and results of these executions must be stored in traces that sync committee collects from the EVM while re-executing the blocks. 
This PR adds collecting and serializing these traces + fixes couple of bugs found while testing with the placeholder part
> tracer: keccak opcode tracing

- niljs/src/utils/receipt.ts
- niljs/test/integration/deploy.test.ts
- niljs/test/integration/helpers.ts
Optimisation and speeding for contact deployment and sending transactions
- WaitTillMainShard default set to false
- Fix cases for failed external transactions
Fixed https://github.com/NilFoundation/nil/issues/125
> niljs: handle failed external failed

- nil/internal/collate/block_listener.go
- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/services/rpc/rawapi/proto/block.proto
Such approach should be more network-friendly than request blocks by batches. Here we send blocks one by one in a following way: [header (message size)] [message].
> [syncer] use stream instead of request-response

- .github/workflows/main.yml
Corrected an [inattention](https://github.com/NilFoundation/nil/pull/158#discussion_r1949294829) from a previous PR
> [GH-65] Path to executable fixed

- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/proposer_test.go
- nil/services/synccommittee/internal/rollupcontract/abi.json
- nil/services/synccommittee/internal/rollupcontract/commit_batch.go
- nil/services/synccommittee/internal/rollupcontract/errors.go
- nil/services/synccommittee/internal/rollupcontract/eth_client.go
- nil/services/synccommittee/internal/rollupcontract/utils.go
- nil/services/synccommittee/internal/rollupcontract/wrapper.go
- Update L1 rollup contract abi, adjusted proposer code to use updated version (including batch tx creation). 
- Add offchain checks for `UpdateState` input data to avoid `execution reverted` errors. 
There are two kind of errors that are ignored while submitting blob and state updating. If the batch is already commited, we skip `commitBatch` call, if it is already finalized, we skip `updateState` as well.
> synccomittee(proposer): update to new L1 rollup contract, add blob tx

- nil/internal/collate/proposer_test.go
- nil/internal/config/config.go
- nil/internal/config/params.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/testaide.go
- nil/internal/execution/zerostate.go
- nil/internal/execution/zerostate_test.go
- nil/internal/vm/errors.go
- nil/internal/vm/precompiled.go
- nil/services/synccommittee/prover/tracer/state_db.go
- nil/tests/basic/basic_test.go
- nil/tests/config/config_test.go
Before this patch it was valid to send messages to non-exising shards. That caused different errors during getting receipts for messages that contained such messages.
This patch adds some validation for that. Fix is pretty straightforward since we don't have "nShards" as a separate option we get an array of gas prices because amount of elements is exactly shard count.
Closes #85
> [execution] validate shardId for outgoing messages

- nix/npmdeps.nix
- package-lock.json
This diff updates the lockfile so that `next build` no longer fails in `docs_ai_backend` and Ansible provisioning works for `nil-docs`.
> [docs] fix to ansible on nil-docs

- nil/common/logging/fields.go
- nil/internal/collate/bootstrap.go
- nil/internal/collate/syncer.go
- nil/internal/config/params.go
- nil/internal/consensus/ibft/validators.go
- nil/internal/execution/state.go
- nil/internal/signer/block_verifier.go
- nil/services/nilservice/service.go
- nil/tests/archive_node/archive_node_test.go
- nil/tests/async_await/async_await_test.go
- nil/tests/cli/cli_test.go
- nil/tests/common.go
- nil/tests/config/config_test.go
- nil/tests/consensus/consensus_test.go
- nil/tests/faucet/faucet_test.go
- nil/tests/rpc_node/rpc_node_test.go
- nil/tests/rpc_suite.go
- nil/tests/shard/shard_test.go
- nil/tests/sharded_suite.go
- nil/tests/timeouts_no_race.go
- nil/tests/timeouts_race.go
This patch enables consensus for the main shard. Now, it is validated by all available validators.
The list of validators is simply a collection of validators from all shards without duplicates.
The main issue is the tests since the sharded suite now has to wait for the zero shard to start ticking.
Need for #143
> [consensus] run consensus on main shard by all validators

- nil/cmd/nild/main.go
- nil/common/logging/logger.go
- nil/common/logging/logger_test.go
Log filter allows specifying which log components are enabled.
Filter is a string in the following format: `"[-]component1:[-]component2:..."`, where `-` indicates that a component is disabled, `:` is separator.
For example:
- `all:-consensus:-collator` will print all logs except `consensus` and `collator`.
- `-all:execution` will print only `execution` logs.
Now, it is used only in `nlid` via `--log-filter` command line argument.
> Introduce logs filter

- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/testaide.go
As in some previous patches we faced with an issue that made an assumption that we should use last block from some chain. However, it seems not so and we should exactly specify blockHash for processing. To avoid such failures in future let's add panic here but only in debug mode. We had the same panic before but it was pretty easy to trigger it from third-party side.
> [syncer] fix prev block hash mismatch error on sync

- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/contract_test.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/postprocess.go
- nil/internal/execution/state.go
- nil/internal/execution/testaide.go
- nil/services/rpc/filters/filters_test.go
- nil/services/rpc/jsonrpc/debug_api_test.go
- nil/services/rpc/jsonrpc/eth_accounts_test.go
- nil/services/rpc/jsonrpc/eth_receipt_test.go
- nil/services/rpc/jsonrpc/eth_transaction_test.go
- nil/services/rpc/jsonrpc/send_transaction_test.go
- nil/services/rpc/jsonrpc/test_block.go
- nil/tests/common.go
- nil/tests/consensus/consensus_test.go
The following is fixed:
- Don't replay block if its MainShardBlock was not porcessed in this node yet. Otherwise, on-chain config will be incorect as it is bound to the main block.
- Commit replayed block(write to database) only after validation succeed. To be able to do that, some refactoring in block building was made.
Also, Syncer's logger name was changed - not it contains synced shard and active shards. It allows to better understand which syncer the log belongs to.
> [syncer] Fix syncer

- .github/workflows/main.yml
we're out of CI runners capacity right now, thus `macos-15-large` builds constantly fail due to runner allocation problems
this patch temporary disables the build
> disable macos-15-large build for a while

- nil/cmd/nild/devnet.go
Main shard is not self-sufficient right now. So we need to modify zerostate generation according new approach.
Follow-up d5a78c76c34079678940fafca8bbdd604cb181a1
> [gen-config] fix zerostate generation

- nil/Makefile.inc
- nil/contracts/generate.go
- nil/contracts/solidity/system/L1BlockInfo.sol
- nil/internal/collate/proposer.go
- nil/internal/collate/scheduler.go
- nil/internal/config/config.go
- nil/internal/config/generate.go
- nil/internal/config/params.go
- nil/internal/contracts/contract.go
- nil/internal/execution/state.go
- nil/internal/execution/transactions.go
- nil/internal/execution/zerostate.go
- nil/internal/types/address.go
- nil/internal/types/block.go
- nil/internal/types/ssz_test.go
- nil/internal/types/transaction.go
- nil/services/cliservice/block_format_test.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/services/rollup/eth.go
- nil/services/rollup/l1_fetcher.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/synccommittee/prover/tracer/state_db.go
- nil/tests/common.go
- nil/tests/l1info/l1info_test.go
- nil/tests/rpc_suite.go
- nil/tests/sharded_suite.go
- smart-contracts/contracts/Nil.sol
L1 Block fetcher is a service that fetches information about Ethereum blockchain and stores it in the on-chain config.
The workflow is as follows:
1. Poll Ethereum RPC nodes for new blocks at some interval.
2. Once new block is fetched, create new transaction to `L1BlockInfo` contract with L1blockInfo in calldata.
3. `L1BlockInfo` contract writes L1 block info to the config parameter `l1info`.
4. L1 block info is updated and stored in the on-chain config. Go to 1.
> Introduce L1 Block fetcher

- nil/internal/collate/scheduler.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
Right now syncer is responsible for zerostate generation.
> [collate] drop unused config options

- explorer_frontend/src/features/contracts/assets/arrow-circle-up.svg
- explorer_frontend/src/features/contracts/components/Contracts/Contract.tsx
- explorer_frontend/src/features/contracts/components/Contracts/Contracts.tsx
- explorer_frontend/src/features/contracts/components/Contracts/SmartAccountNotConnectedWarning.tsx
We have a problem in explorer that when user does not have a connected/deployed smart account we don't disable contract management panel and allow to deploy/import/call smart contracts (which evidently fails).
To make it easier to understand for a user what their first action should be, we need to disable contract management panel and show a warning instead, saying that smart account should be connected first.
> Show warning in playground if sa is not connected

- explorer_frontend/src/features/account-connector/init.ts
- explorer_frontend/src/features/code/init.ts
- explorer_frontend/src/features/code/model.ts
- explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
- explorer_frontend/src/features/contracts/components/Deploy/ShardIdInput.tsx
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/base.ts
- explorer_frontend/src/features/shards/init.ts
- explorer_frontend/src/features/shards/models/model.ts
- explorer_frontend/src/pages/playground/PlaygroundPage.tsx
This diff adds shard id validation to deploy contract modal. The motivation is to improve UX, especially for newcomers who need to see concrete errors while trying to deploy on a nonexistent shard.
https://github.com/user-attachments/assets/6201e7a9-86eb-4de0-bad9-98778c1e0683
> Add shardid validation to deploy modal

- explorer_frontend/src/features/transaction/components/Transaction.tsx
This PR solves [this](https://github.com/NilFoundation/nil/issues/117) issue. Transaction routing to overview is fixed. Initially, when you click on a tx hash in the outgoing or incoming message tab, it would route to outgoing or incoming message tab respectively, instead of the overview of the tx hash. But upon this PR it would redirect you to the overview.
> added transaction routing to overview

- explorer_frontend/src/features/contracts/components/Management/ContractManagement.tsx
This PR fixes the issue mentioned [here](https://github.com/NilFoundation/nil/issues/259), where the contract balances are shown in Ether rather than Wei to maintain consistency in terms of values with respect to every mentioning of values.
> fixed formatting of balances in contract management

- nil/internal/collate/syncer.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/zerostate.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/services/rpc/jsonrpc/types.go
In this PR, we aim to replicate data across all shards for the validator, even if the validator is not actively validating a specific shard (#54). To ensure this, it’s crucial that the zeroStateConfig is consistent across all validators. To achieve this, we will share the publicMainKey with them.
> [syncer] Replicate data from all shards.

- wallet-extension/package.json
I accidentally ran `npm install clean` and not `npm ci` and installed some random package. It needs to be removed as it is not used and may not even be safe
> remove unused dep in wallet extension

- explorer_frontend/src/features/account-connector/components/MainScreen.tsx
- explorer_frontend/src/features/contracts/components/Contracts/Contract.tsx
- explorer_frontend/src/features/contracts/components/Contracts/Contracts.tsx
- explorer_frontend/src/features/healthcheck/components/NetworkErrorNotification.tsx
- explorer_frontend/src/features/healthcheck/index.ts
- explorer_frontend/src/features/healthcheck/init.ts
- explorer_frontend/src/features/healthcheck/model.ts
- explorer_frontend/src/init.ts
- explorer_frontend/src/pages/playground/PlaygroundPage.tsx
When rpc api is inaccessible or user has an invalid rpc url, we want to let them know something is wrong.
We are going to display a warning if api is inaccessible and disable some UI features as well.
RPC check is made every 10 seconds or on any endpoint change. If user is not on the page the check is not made for the sake of optimizing resources.
> Add playground rpc api healthcheck

- .github/workflows/main.yml
currently macos builds don't have any caching. this is rly frustrating, cause every CI checks takes 1h+
for sure we'll fix this later, but as a temporary solution I propose to disable em
> disable macos builds

- nil/client/direct_client.go
- nil/common/logging/ch_logger.go
- nil/common/logging/fields.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/services/rpc/httpcfg/http_cfg.go
- nil/services/rpc/jsonrpc/eth_api.go
- nil/services/rpc/jsonrpc/eth_api_test.go
- nil/services/rpc/jsonrpc/send_transaction.go
- nil/services/rpc/server.go
- nil/services/rpc/transport/handler.go
- nil/services/rpc/transport/handler_test.go
- nil/services/rpc/transport/server.go
- nil/services/rpc/transport/server_test.go
- nil/services/rpc/transport/types.go
this PR adds some logging based on RPC request headers. mostly for debugging and understanding whether client functionality works properly as we release new versions of our CLI / wallet / nil.js
also it reworks a bit our mechanism for event writing to ClickHouse. since we reused `zerolog` interface here (which is rly convenient), there's one small caveat: we need to control global logging level. otherwise event logging may be occasionally disabled
> [rpc] log client RPC events

- nil/services/rpc/filters/filters.go
Sometimes we get following issue in CI:
```
../../services/rpc/filters/filters.go:177 > processBlockHash failed error="DB::Get key: \"Blocks:0:\\x00\\x00)\\x91\\b)F\\x1d\\x0f\\x1d\\x8e\\xb2C\\xac\\x9f\\x1c\\xe7Y\\x03\\x94\\bai$\\x05\\xa7\\x80\\x1c3\\x11\\xe0\\xcb\" error: DB Closed
```
That happens because we had sleep that couldn't be interrupted by context cancellation. This patch fixes it.
> [filters] fix polling in case of context cancellation

- explorer_frontend/src/features/contracts/components/Deploy/DeployContractModal.tsx
- explorer_frontend/src/features/contracts/components/Deploy/ImportContractTab.tsx
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/base.ts
- explorer_frontend/src/features/logs/init.tsx
Currently we have a severe issue with importing existing contract feature in playground. User can set any address to input, even the address of nonexistent contract (any valid Hex string) and import will not fail. Moreover the fake contract will appear in the project and can cause a lot of misunderstanding.
This is fixed just by checking the code of the contract before importing it. It `getCode()` returns `0x` it means nothing is deploy at address.
Additionally this diff fixes remnants in the code of "assign smart contract" naming.
> Throw error if in playground import nonexistent smart contract

- nil/services/rpc/filters/filters.go
- nil/tests/cli/cli_test.go
Sometimes it fails with an error:
```
Error: abi: attempting to unmarshall an empty string while arguments are expected
```
That means we try to call contract before it was included into main. That's how eth_call works for now. This patch adds some delay to be sure that contract is ready to use.
> [tests] make TestCliCometa more reliable

- nil/internal/abi/abi.go
- nil/services/synccommittee/prover/tracer/state_db.go
- nix/solc.nix
- **`abi.go`**:  
- Fixed wording in comments: `"invokable"` → `"invocable"`  
- **`state_db.go`**:  
- `"finilized"` → `"finalized"`  
- `"requre"` → `"require"`  
- `"occures"` → `"occurs"`  
- **`solc.nix`**:  
- `"avaliable"` → `"available"`  
- `"reenable"` → `"re-enable"`
> Fix spelling errors 

- nil/tests/nil_load_generator_service/nil_load_generator_test.go
Now tests for load generator is flaky. We reason - we don't have enough time to generate SmartAccounts, that's why in this PR increased waiting time for this operation.
> [loadgen] Increase waiting time

- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/base.ts
We had a discussion about shard id and decided to change a little the mechanics of shard id.
What we want:
- When user opens modal initially and there is no previously used shard id, we need to set as a default value any random number in the range from `0` to `shards amount`.
- When user opens modal second time, we need to preserve previously used shard id, because it is more probable theat user is going to use it again.
- Important notes - always trigger validation on default value
> Set initial random shard-id in playground

- nil/cmd/proof_provider/main.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/service_test.go
- nil/services/synccommittee/proofprovider/service.go
- nil/services/synccommittee/proofprovider/task_handler.go
- nil/services/synccommittee/proofprovider/task_handler_test.go
**Add mode `skip-proof` for prover:**  run without actual proof. It useful when need to check whole pipeline without powerful prover network.
**Allow start sync committee service without L1 contract access** for check main functionality even no access to L1 contract.
> [sync committee] Enable skip mode

- docs/nil/intro.mdx
This diff removes the 'New release' card from the index page because it will no longer refer to the actual new release and there's no corresponding migration guide to link the new card to.
> [docs] card removal to avoid confusion

- nil/internal/collate/proposer.go
- nil/internal/config/config.go
- nil/internal/config/params.go
- nil/internal/execution/state_accessor.go
- nil/internal/execution/transactions.go
- nil/internal/types/block.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/rpc/rawapi/local_block.go
- nil/services/rpc/rawapi/pb/conversion.go
- nil/services/rpc/rawapi/proto/block.proto
- nil/services/synccommittee/prover/tracer/copy_tracer.go
- nil/services/synccommittee/prover/tracer/keccak_tracer.go
- nil/services/synccommittee/prover/tracer/state_db.go
- nil/services/synccommittee/prover/tracer/tracer.go
- nil/services/synccommittee/prover/tracer/tracer_mock_client_test.go
- nil/services/synccommittee/prover/tracer/utils.go
To enhance the tracing capabilities for a broader set of contracts, several new methods need to be implemented: `AddToken`, `SubToken`, `SetTokenTransfer`, `AddRefund`, `SubRefund`, and `GetGasPrice`. This pull request enables us to gather traces from every block produced by the `nil_load_generator`. 
Additionally, a bug in the copy tracer has been fixed; previously, there was a discrepancy between the execution EVM and the tracer EVM during the deployment transaction.
> prover: implement token methods, gas price, fix copy tracer on deploy

- nil/common/concurrent/suspendable.go
- nil/common/concurrent/suspendable_test.go
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/service_test.go
* Introduce the `Suspendable` struct, enabling periodic tasks to be paused and resumed;
* Integrated this into the `Aggregator`;
Critical (non-retryable) error submitted by the `Proof Provider` should trigger soft reset of the Sync Committee.
For that, `Aggregator` should support suspension and scheduled resume.
New `Aggregator.Pause()` and `Aggregator.Resume()` methods will be called from `core/taskStateChangeHandler` during Sync Committee's soft state reset (as part of top-level error handling) in a follow-up PR
> Sync Committee: Suspendable Aggregator

- explorer_frontend/src/features/account-connector/init.ts
This diff adds `BigInt` conversion to 1e18 value to fix niljs error "Integer out of safe range". In Javascript such values should be used with `bigint` type.
> Fix integer out of range error on smart account topup in Playground

- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/aggregator_test.go
- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/proposer_test.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/core/service_test.go
- nil/services/synccommittee/core/task_state_change_handler.go
- nil/services/synccommittee/internal/rpc/client.go
- nil/services/synccommittee/internal/rpc/task_debug_rpc_test.go
- nil/services/synccommittee/internal/scheduler/task_result_sender.go
- nil/services/synccommittee/internal/scheduler/task_result_sender_test.go
- nil/services/synccommittee/internal/scheduler/task_scheduler.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/storage/task_result_storage.go
- nil/services/synccommittee/internal/storage/task_result_storage_test.go
- nil/services/synccommittee/internal/storage/task_storage.go
- nil/services/synccommittee/internal/storage/task_storage_test.go
- nil/services/synccommittee/proofprovider/task_handler.go
- nil/services/synccommittee/proofprovider/task_handler_test.go
- nil/services/synccommittee/proofprovider/task_state_change_handler.go
- nil/services/synccommittee/prover/task_handler.go
These changes are aimed to decouple storage-related logic of core SC components (mainly `Aggregator` and `Proposer`) and ease ongoing development of `Observer`
* Separated block storage functionality into distinct interfaces: `AggregatorBlocks`, `ProposerBlocks` and `ProvedBlockSetter`;
* Updated related code and tests to use these new interfaces;
* Moved `TaskStorage` and `TaskResultStorage` from `storage` package to the packages which use them;
* Declared new interfaces `AggregatorTasks`, `HandlerTasks` and `TaskResultSaver` with limited sets of methods;
> Sync Committee: Storage interfaces refactoring

- nil/internal/collate/block_listener.go
- nil/internal/collate/proposer.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/config/config.go
- nil/internal/execution/Makefile.inc
- nil/internal/execution/block_generator.go
- nil/internal/execution/fee.go
- nil/internal/execution/state.go
- nil/internal/types/collator.go
- nil/tests/cometa/cometa_test.go
- nil/tests/economy/economy_test.go
Before this patch we had following schema:
Main shard proposer should choose main shard hashes and send them to validators.
Validators update main shard config with corresponding gas prices of that shards.
Such schema has following pitfalls: we have all syncers dependent from each other
because main shard should be able to read their gas prices. And other shards
need a config from main shard. Such approach makes synchronization quite complex:
main shard should wait 1+ shards and 1+ shards should wait for the main shard.
After this patch validation of main shard will be independent because
we include gas prices of shard blocks into proposal.
Reverse operation is performed by using gas prices from configuration.
> [execution] make main shard validation self-sufficient 

- nil/cmd/nild/devnet.go
- nil/contracts/solidity/tests/Token.sol
- nil/internal/collate/bootstrap.go
- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/db/tables.go
- nil/internal/network/addr_info.go
- nil/services/nilservice/service.go
Anyway we decided that all validator/archive_nodes replicate all data of all shards. So no need to support per-shard snapshotting.
> [syncer] drop per-shard snapshot bootstrap

- explorer_frontend/src/features/account-connector/components/EndpointScreen.tsx
If endpoint is saved in the store  it will trigger wallet creation. Which means that if you open wallet it will show loading on endpoint page. Usually when network is live this is done fast so you don't see it, but if network is down we have strange ui where something is loading but input is empty
> set wallet input if endpoint exists

- explorer_frontend/src/features/account-connector/init.ts
- explorer_frontend/src/features/code/init.ts
- explorer_frontend/src/features/code/model.ts
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/logs/init.tsx
We actually don't display compilation warnings in Playground compiler.
What this diff does - is display of compilation warnings instead of `Compilation successful` log.
> Show warnings on solidity compilation in playground

- explorer_frontend/src/features/account-connector/ActiveComponent.ts
- explorer_frontend/src/features/account-connector/components/AccountContainer.tsx
- explorer_frontend/src/features/account-connector/components/MainScreen.tsx
- explorer_frontend/src/features/account-connector/components/RpcUrlScreen.tsx
- explorer_frontend/src/features/account-connector/init.ts
- explorer_frontend/src/features/account-connector/model.ts
- explorer_frontend/src/features/account-connector/validation.ts
- explorer_frontend/src/features/cometa/init.ts
- explorer_frontend/src/features/cometa/model.ts
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/base.ts
- explorer_frontend/src/features/healthcheck/init.ts
- explorer_frontend/src/features/healthcheck/model.ts
- explorer_frontend/src/features/tokens/init.ts
We've already renamed endpoint to rpc url in the interface, but in code it is still a mismatch in names.
This diff changes nothing functionally, only renames `endpoint` in the code where it should be `rpc url`.
> Rename endpoint to rpcUrl in the code

- explorer_frontend/src/features/code/Code.tsx
Actually currently we have a built-in "find and replace" dialog in the code field. But due to some css styling it was typically hidden. Find and replace dialog should be always visible because it is needed to go from one fragment of code to another without loosing find and replace panel.
https://github.com/user-attachments/assets/9e2110a7-4b92-4808-8c22-e97fbfaf9c73
> Fix find and replace dialog in playground

- nil/cmd/nild/devnet.go
- nil/cmd/nild/main.go
- nil/services/nilservice/config.go
Currently we run multiple instances in production, and pprof port is always 6600 without any ability to override it. This means that only one instance (randomly) succeeds at opening this port first, and we can only connect to that specific instance to get profiling information.
Right now we're trying to figure out a few bugs that happen where an ability to take stack trace of all threads is very important. Thus, this PR makes pprof port configurable.
> Allow to specify pprof port in nild command-line arguments

- nil/services/faucet/jsonrpc.go
Closes https://github.com/NilFoundation/nil/issues/95
The legacy faucet was removed some time ago, so we can explicitly track seqnos for faucet contracts.
> [faucet] Actually track seqnos in the service

- nil/internal/collate/bootstrap.go
- nil/internal/collate/syncer.go
Fetching of snapshot is optional. We still can apply blocks one by one. We should log errors but not terminate application in case of issues.
Follow-up 5505b9171eae3e4f0d612b58de66e1bee4f877bb
> [syncer] don't abort bootstrap if snapshot is not fetched

- nil/contracts/solidity/tests/RequestResponseTest.sol
- nil/internal/execution/state.go
- nil/tests/async_await/async_await_test.go
- nil/tests/rpc_suite.go
If the callee of `sendRequest` also calls `sendRequest`, it leads to incorrect inheritance of the request chain.
`sendRequest` should not wait for another `sendRequest`, it should wait for only `awaitCall`.
Three new test cases covering these statements have been added.
> [execution] Fix nested sendRequests

- nil/cmd/nil_load_generator/main.go
- nil/cmd/nild/devnet.go
- nil/internal/collate/syncer.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/testaide.go
- nil/internal/execution/zerostate.go
- nil/internal/execution/zerostate_test.go
- nil/services/nil_load_generator/service.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/tests/async_await/async_await_test.go
- nil/tests/block_replay/block_replay_test.go
- nil/tests/cli_call/cli_call_test.go
- nil/tests/cometa/cometa_test.go
- nil/tests/config/config_test.go
- nil/tests/deploy/deployment_test.go
- nil/tests/economy/economy_test.go
- nil/tests/modifiers/rpc_modifiers_test.go
- nil/tests/multitoken/multitoken_test.go
- nil/tests/nil_load_generator_service/nil_load_generator_test.go
- nil/tests/opcodes/opcodes_test.go
- nil/tests/regression/regression_test.go
- nil/tests/rpc_suite.go
- nil/tests/sharded_suite.go
- nil/tests/smart-account/smart_account_test.go
In the future we need to get rid of generation mainKeys inside our cluster. But for now for replication - the best way to share them inside configuration and generate new one if we don't do it.
> Add main keys to configuration

- explorer_frontend/src/features/code/Code.tsx
- explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/base.ts
This diff improves UX by displaying deployment errors in the Deploy modal itself as long as in the logs panel. Previously errors were displayed only in the logs, which was not visible when modal was open (cz it has a backdrop).
> Add duplication of deployment errors to deploy modal

- nil/internal/collate/block_listener.go
- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/config/config.go
- nil/internal/config/params.go
- nil/internal/consensus/ibft/validators.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/state.go
- nil/internal/execution/testaide.go
- nil/internal/execution/transactions_test.go
- nil/internal/execution/zerostate_test.go
- nil/internal/readthroughdb/read_through.go
- nil/internal/signer/block_verifier.go
- nil/services/rpc/jsonrpc/eth_block_test.go
- nil/services/rpc/jsonrpc/eth_call_test.go
- nil/services/rpc/jsonrpc/send_transaction_test.go
- nil/services/rpc/rawapi/local_call.go
- nil/tests/read_through/read_through_db_test.go
We decided to change approach to configuration management a bit. At the moment of block generation (with height=h) we have committed known block (h-1). This block has a link to mainShardHash that is a base for config accessor.
Such approach is quite consistent and decrease chances to face with an issue when we don't have an access to main shard block because it's not replicated yet.
> [execution] unify config accessor management between gas prices and validators

- nil/services/faucet/jsonrpc.go
- nil/tests/faucet_service/faucet_service_test.go
- nil/tests/rpc_suite.go
Updated the tests so that they reproduce the seqno gap problem that occurred on dev stand.
Fixed it by reverting the recent introduction of seqno cache in the faucet service.
The current solution (fetching seqno each time) is weak, but works better than caching that poses problems of invalidation.
> [faucet] Fix seqno tracking + test update

- go.sum
- nil/contracts/solidity/tests/Test.sol
- nil/internal/execution/state.go
- nil/tests/cli_call/cli_call_test.go
- nil/tests/common.go
- nil/tests/consensus/consensus_test.go
- nil/tests/regression/regression_test.go
- nil/tests/rpc_suite.go
- smart-contracts/contracts/Faucet.sol
We had problems with consensus. That's because the same EVM input produced different output that led to hash mismatch error. It was pretty hard to debug this issue. It broke consensus on load gen tests because uniswap sometimes operates with a time.
This patch removes using of `time.Now()` that breaks an idea of repeatable blockchain history.
Our block.Timestamp is always zero. So I suggest to use block.Id as a logical time. It also monotonically increases.
> [execution] use deterministic time

- docs/nil/guides/app-migration.mdx
- uniswap/tasks/token/README.MD
after opensourcing the main repo there's no need in a separate `uniswap-v2` example repo and it's gonna be archived soon
> set uniswap docs links to refer to in-repo implementation

- docs/nil/hardhat/getting-started.mdx
- docs/nil/nild.mdx
- docs/nil/niljs/tokens.mdx
- docs/nil/smart-contracts/tokens.mdx
- docs/sidebar-nil.js
- docs/tests/FT.sol
- docs/tests/compilationCommands.js
- docs/tests/multi-tokens-support.test.mjs
- docs/tests/working-with-smart-contracts-niljs.test.mjs
- explorer_frontend/README.md
This diff closes several minor GitHub issues and addresses comments received in other channels.
* Closes #351 by amending links to config files when running `nild`
* Closes #291 by adding a simple FT example to docs
* Improves the description of `npm run build` in the Hardhat tutorial
* Adjusts Nil.js snippets in several tutorial
* Fixes =nil; CLI sidebar by removing the duplicate section and restoring 'Error handling'
> [docs] miscellaneous fixes

- explorer_frontend/src/features/contracts/components/Deploy/DeployContractModal.tsx
- explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
This diff fixes #377 by adjusting height of the container.
In addition, it makes deploy modal non-closable when deploy or import of a contract is pending to provide smoother ux.
> Fix playground deploy button position in modal

- nil/internal/collate/block_listener.go
- nil/internal/network/config.go
- nil/internal/network/dht.go
- nil/internal/network/manager.go
- nil/internal/network/pubsub.go
- nil/internal/network/req_resp.go
- nil/internal/network/testaide.go
- nil/services/txnpool/txn_exchange.go
Seems we have a conflict for archive node test. Exact reason why messages signed by different validators are accepted is a seprate task. But to make test more stable let's add custom prefix to our network protocols.
By default it's `/nil`.
> [network] add custom prefix to network protocols

- explorer_backend/services/tutorials_db.ts
- nix/nilexplorer.nix
This diff fixes explorer backend startup by removing `AUTOINCREMENT`, we can do it because SQLite automatically assigns a unique id (without needing `AUTOINCREMENT`).
In addition this patch adds a simple check that command `npm start` does not fail.
> Fix explorer backend startup sql issue

- explorer_backend/start.ts
This diff temporary disables generation of tutorials in explorer backend. We need to fix some issue with it before running in production.
> Temporary disable tutorials explorer backend generation

- nil/internal/types/address.go
- nil/internal/types/address_test.go
That's not the way we calculate addresses, so this func is misleading.
Reported by Amir in a Slack thread.
> [cleanup] Remove misleading func PubkeyBytesToAddress

- niljs/src/clients/BaseClient.ts
This patch is changing `niljs` client's class `transport` property modifier. We often want to use it like `smartAccount.client.transport`. And, generally there is no sense in protected property usage here.
> Niljs faucet allow topup in Number and change client transport prop to readonly

- nil/services/rpc/rawapi/local_system.go
- nil/tests/rpc_suite.go
Before execute transaction we need to wait until shards start to ticks.
> [tests] Wait until shards start to tick

- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/testaide/blocks.go
- nil/services/synccommittee/internal/types/blocks.go
- nil/services/synccommittee/internal/types/errors.go
As part of the Soft State Reset logic, introduced several changes to the `BlockStorage` type:
* Implemented `BlockStorage.ResetProgress(hash)` method, which performs a state reset starting from the given main block hash (including stored exec shard blocks and the latest fetched refs);
* Added new tests: `Test_ResetProgress_Block_Does_Not_Exists()` and `Test_ResetProgress()` with multiple test cases for block reset logic;
* BlockStorage.getBlockEntry(id) method now accepts an additional `required bool` parameter and returns `scTypes.ErrBlockNotFound` error if the required block is not found;
* Added `scTypes.ErrBlockNotFound` to the list of errors ignored by `badgerRetryRunner`;
> Sync Committee: Block Storage Reset

- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/consensus/ibft/validators.go
- nil/internal/consensus/ibft/verifier.go
- nil/services/nilservice/service.go
- nil/tests/sharded_suite.go
The main idea is to make validator as an entry point for proposal insertion.
We insert proposal in two cases: consensus and block replay.
Sometimes we had an error "Transaction conflict" caused by race between
that two modules. So it seems reasonable to add a lock here to
avoid confusing error messages and execution transaction two times.
> [collate] prevent "Transaction conflict" error because of syncer/consensus race

- explorer_frontend/src/features/code/assets/HandlingExtTxExample.sol
- explorer_frontend/src/features/contracts/init.ts
This PR fixes issue [392](https://github.com/NilFoundation/nil/issues/392). It changes the state mutability of a function in the contract which would throw compiling error otherwise. This PR also fixes a bug where bytes input types in constructor were incorrectly processed, leading to unexpected behaviour which is it would result in errors such as `t.replace` is not a function . Previously, the bytes case returned true instead of the actual input value due to improper type coercion.
> Fixed a bug in Handling External Transactions example contract

- flake.nix
file `./nix/docstutorialsservice.nix` was removed in [this pr](https://github.com/NilFoundation/nil/pull/274)
> remove docstutorialservice from nix flake

- docs/README.md
- docs/package.json
- docs/run_tests.sh
- docs/tests/globals.js
This diff removes hardcoded RPC URL from docs' tests. It was there previously when the repo was still closed but now it's been exposed to the public.
> [docs] removal of hardcoded tokens

- explorer_frontend/src/features/account-connector/components/MainScreen.tsx
This PR solves the bug mentioned [here](https://github.com/NilFoundation/nil/issues/304). Currently, the RPC input, after connecting the wallet is a readOnly input and would confuse users form trying to edit as it appears as a normal input box where you can click on it and the borders get highlighted, just as every input box getting active. This PR would make the RPC input box inactive and not allow for focussing so that it behaves as a non-interactive UI component, removing a confusion for the interaction with the input box.
> Fix issue with playground RPC input hidden border

- explorer_frontend/src/features/account-connector/init.ts
Currently, the conversion of amount for topping up is not parsed correctly, as NIL token and other tokens have different decimals. This PR fixes the conversion of the amount to bigint and number respectively for topping up of NIL and other tokens.
> Fix conversion of amount during top-up

- .gitignore
- README.md
- explorer_frontend/src/features/contracts/components/Deploy/ShardIdInput.tsx
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/models/shardsAmount.ts
- explorer_frontend/src/features/shards/models/model.ts
- nil/client/client.go
- nil/client/direct_client.go
- nil/client/rpc/client.go
- nil/services/rpc/jsonrpc/doc.go
- nil/services/rpc/jsonrpc/eth_api.go
- nil/services/rpc/jsonrpc/eth_shards.go
- nil/services/rpc/rawapi/api.go
- nil/services/rpc/rawapi/client.go
- nil/services/rpc/rawapi/local_system.go
- nil/services/rpc/rawapi/node.go
- nil/services/rpc/rawapi/server.go
- nil/tests/basic/basic_test.go
- niljs/src/clients/PublicClient.test.ts
- niljs/src/clients/PublicClient.ts
This diff adds a new methods to `niljs` client  - `getShardIdList()` and `getNumShards()`. `getNumShards()` returns the amount if shards. We decided to migrate to usage of this rpc method in playground to decrease connectedness between playground and explorer backend.
In addition this diff implements `getNumShards()` on the side of rpc.
It adds `openrpc.json` to `.gitignore` because we don't want to commit auto-generated file accidentally.
> Use eth_getShardIdList to get shards amount in playground

- explorer_frontend/src/features/code/init.ts
- explorer_frontend/src/features/contracts/components/Management/MethodInput.tsx
This diff fixes the issue with initial values in multiple inputs displayed as `undefined`.
https://github.com/user-attachments/assets/0e68e06e-966e-4480-a426-ccf2d14f6c77
Also, it resets `$error` on successful compilation of the code. We use this `$error` to display error in code editor, and previously we used to remove error only on code change, but successful compilation can happen for instance after changing compiler version without any changes to the code. This is the reason to reset `$error` on successful compilation as well.
> Fix multiple inputs in playground sc management

- explorer_frontend/src/features/logs/components/TxDetails.tsx
- explorer_frontend/src/features/logs/hooks/useRepeatedGetTxByHash.ts
Before this patch we had an issue with infinite fetching transaction details in case of an error.
This diff adds `clearInterval(intervalId);` to stop trying fetch transaction if once it threw an error.
Also it brings minor styling improvements for an error message.
> Fix fetching tx details in playground logs

- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/testaide.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/postprocess.go
- nil/internal/execution/state.go
- nil/internal/execution/state_trace.go
- nil/internal/types/transaction.go
- nil/services/rpc/jsonrpc/debug_api_test.go
- nil/services/rpc/jsonrpc/test_block.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/txnpool/queue.go
- nil/services/txnpool/tree.go
- nil/services/txnpool/txnpool.go
- nil/services/txnpool/txnpool_test.go
Reduced the calls to the expensive `Hash()` method of `Block` and `Transaction` to more or less necessary amount.
While looking at ways to implement https://github.com/NilFoundation/nil/issues/97, I decided to optimize the code, since there aren't many places where blocks and txns are hashed.
Now transaction hashes are calculated at the following places in validators:
1. Pool: all added txns.
2. Proposer: all incoming internal txns (not forwarded; external txn hashes are taken from the pool).
3. Proposal validation: block execution.
4. Proposal commit: block execution.
5. Block execution: all incoming and outgoing (generated during execution) txns.
Changes made:
1. Proposer fetches txns from the pool along with their hashes (`MetaTxn`).
2. Pool discards txns by hash.
3. …
> [optimization] Reduce block and txn hashing via reuse

- .github/workflows/build_artifacts.yml
- Makefile
- go.mod
- go.sum
- nil/internal/network/pubsub.go
- nil/tools/tools.go
- nix/nil.nix
See #420
We will need to deal with all the warnings that are now generated before enabling it for the whole project.
<details>
<summary>Analysis of the entire project</summary>
```
$ find ./nil -type f -name "*.go" \
| xargs -I {} dirname {} \
| sort -u \
| xargs -I {} sh -c 'echo ">> Checking {}" && GOFLAGS="-tags=test" go run gvisor.dev/gvisor/tools/checklocks/cmd/checklocks {}'
>> Checking ./nil/client
>> Checking ./nil/client/rpc
>> Checking ./nil/cmd/cometa
>> Checking ./nil/cmd/exporter
>> Checking ./nil/cmd/exporter/internal
>> Checking ./nil/cmd/exporter/internal/clickhouse
>> Checking ./nil/cmd/faucet
>> Checking ./nil/cmd/journald_forwarder
>> Checking ./nil/cmd/nil
>> Checking ./nil/cmd/nil_block_generator
>> Checking ./nil/cmd/nil_block_generator/internal/commands
>> Checking …
```
> [GH-420] Example of checklocks analyzer integration

- nil/cmd/nild/devnet.go
Get public key from public key only in case we successfully load private key
> [generate-config] Fix problem with missing keys.yaml file

- nil/cmd/cometa/main.go
- nil/cmd/nil/common/rpc_client.go
- nil/cmd/nil_block_generator/internal/commands/client.go
- nil/common/version/version.go
- nil/services/cometa/client.go
- nil/services/faucet/client.go
- nil/services/nil_load_generator/client.go
- nil/services/rpc/internal/http/connection.go
I think all our clients already update they cli to a new versions, that's why we don't need to handle corner case with old [revision](https://github.com/NilFoundation/nil/issues/39).
> [nild] Remove BaseRevision

- nil/common/concurrent/suspendable.go
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/aggregator_test.go
- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/core/reset/resetter.go
- nil/services/synccommittee/core/reset/state_reset_launcher.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/core/task_state_change_handler.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/types/blocks.go
As a reaction to one of the following events, the Sync Committee should perform a partial state reset and re-fetch blocks starting from a well-known point in the past:
a) Critical task execution error
b) Block mismatch detection
- Introduced `StateResetLauncher`, which performs a state reset by suspending and resuming the `Aggregator`.
- Declared the `StateResetter` interface with two methods: `ResetProgressPartial(hash)` and `ResetProgressNotProved()`.
- Implemented the `BlockStorage.ResetProgressNotProved()` method, which purges all non-proven blocks and resets the `latestFetched` value to `nil`.
- Integrated `StateResetLauncher`, triggered in case of a critical task execution error.
- Integrated `StateResetter`, triggered when a block mismatch is detected.
- Implemented …
> Sync Committee: Soft State Reset

- nil/internal/execution/zerostate.go
- nil/internal/execution/zerostate_test.go
Fixes `panic: [ZeroState] ctorArgs pack failed: bytes type is neither slice nor array`.
And test that fails on the buggy version
> [zero-state] Fix pubkey serialization

- explorer_frontend/src/features/contracts/init.ts
This PR solves this [issue](https://github.com/NilFoundation/nil/issues/296) where you would get an error or a wrong default result when you query a mapping. This PR would enable this functionality as initially the `input.name` from the `abi` was checked but mapping usually have no name and hence this would not take any args. This PR will add a check to see if the `input.name` is empty string and if so it would take into consideration that it is a mapping and hence extract the arguments in a different manner.
> Added support to interact with a mapping via playground

- nil/services/nil_load_generator/metrics/metrics_handler.go
- nil/services/nil_load_generator/service.go
This PR adds simple metrics for the Uniswap load generator service. It helps us gather statistics and analyze the distribution of calls from SmartAccount to Pair.
> Added simple metrics for loadgen

- nil/internal/telemetry/internal/resource.go
- nix/nil.nix
To fix following issue on nildev:
```
ERROR=failed to initialize metric provider: conflicting Schema URL: https://opentelemetry.io/schemas/1.26.0 and https://opentelemetry.io/schemas/1.27.0
JSON={"level":"error","component":"nil","error":"failed to initialize metric provider: conflicting Schema URL: https://opentelemetry.io/schemas/1.26.0 and https://opentelemetry.io/schemas/1.27.0","caller":"github.com/NilFoundation/nil/nil/services/nilservice/service.go:351","time":"2025-03-04T16:59:45Z","message":"Failed to initialize telemetry"}wq
```
> [otel] fix semconv version

- nil/cmd/nil_load_generator/main.go
- nil/services/nil_load_generator/service.go
- nil/tests/nil_load_generator_service/nil_load_generator_test.go
`cliservice.NewService` accepts the private key of the smart account, with which the corresponding smart account management commands will work. We don't use `MainSmartAccount` for anything in the load generator, so we don't need credentials from it. Instead, we use `Faucet`, which does not require authentication.
At the same time, the presence of the flag introduces an inconvenience for local debugging. Since `MainPrivateKey` is now only saved to the filesystem when using `nil gen-configs`, we can't just do a `nil run` and then direct the load generator to that instance, we have nowhere to get the `MainPrivateKey` file. I think this adds an inconvenience that is not necessary at all in this case. Let our tools require as much bodywork as possible for a minimally working setup.
N.B. Also …
> [loadgen] main-keys-path parameter removed

- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/tests/contracts/GasBurner.sol
- nil/tests/regression/regression_test.go
If a transaction consumed more gas than the block allowed, it just got stuck in the neighbor out tx tree. That prevented the execution of other transactions. This patch should fix it.
See also https://github.com/NilFoundation/nil/issues/79
> [collate] fix tx stucking when it reaches block gas limit

- go.mod
- nil/cmd/nild/main.go
- nil/common/logging/libp2p_logger.go
- nil/services/admin/server.go
Libp2p internally logs some events but it's disabled by default. This patch gives a way to enable it. It can be done via cmd args or via our admin API.
> [nild] support changing log level of libp2p

- wallet-extension/src/features/components/wallet/home/TokenTab.tsx
- wallet-extension/src/features/utils/index.ts
- wallet-extension/src/features/utils/token.ts
This PR improves UX for copying addresses of the custom and mock tokens.
Why we need this is explained in this issue https://github.com/NilFoundation/nil/issues/369
Fixed https://github.com/NilFoundation/nil/issues/369
https://github.com/user-attachments/assets/5a51a3d0-46d5-40da-8ece-8cacaa21f703
> add copy of mock and custom tokens

- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
Removed redundant check on duplicates (the seqno is checked within external validation, which is a more general check than full duplicates).
And also found a problem with the latest proposer fix: if it stops collecting txns when the block is full, it fails to increment its position. Only when all internal txns are processed, the proposer position is updated correctly.
This lead to duplicating internal txns in the test.
The fix is moving `checkLimits()` to the loop condition.
> [proposer] Fix internal txn counting

- nil/internal/execution/block_generator.go
- nil/internal/execution/metrics.go
Currently GasPrice in metrics always zero because we record them before update.
> Set GasPrice metrics only after update them

- nil/services/txnpool/meta_txn.go
- nil/services/txnpool/queue.go
- nil/services/txnpool/txnpool.go
- nil/services/txnpool/txnpool_test.go
- nil/tests/basic/basic_test.go
`Peek` method should be constant and should not modify content of txpool. But it did by calling `heap.Push(q, txn)`, because txn refers to the real metaTx and its `bestIndex` is changed.
Fixed by cloning it. Also added reset of `bestIndex` during popping from the queue.
> [txpool] Fix bug in transactions retrieving

- nil/cmd/nil_block_generator/internal/commands/config.go
0o666 is too strict mode which makes impossible to operate on the domain socket after nil_block_generator finishes its work. Relaxing it to owner RW priveleges
> relax block gen unix socket permissions

- nil/cmd/nild/devnet.go
- nil/cmd/nild/main.go
- nil/internal/collate/bootstrap.go
- nil/internal/collate/syncer.go
- nil/internal/db/badger.go
- nil/internal/network/pubsub.go
- nil/internal/network/req_resp.go
- nil/internal/network/testaide.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/tests/archive_node/archive_node_test.go
- nil/tests/sharded_suite.go
On syncer initialization (called only on a single syncer on the node) the version is checked. Main shard genesis block hash serves as the version, as in the case of exporter.
If local and remote versions differ:
- if `--allow-db-clear`, the existing db is dropped and the snapshot is fetched;
- by default, an error is returned.
Added tests that restart the archive node with and without reset.
For now, before this code is on all the nodes, there is no way to fetch a remote version, so an error there is handled stoically.
> [archive node] Drop on version change

- nil/services/rpc/jsonrpc/types.go
Before this patch it was unclear how much gas block used. We just forgot to add this property to RPCBlock structure. This patch fixes it.
> [rpc] add gasUsed to RPC API block

- wallet-extension/vite.contentScript-nil.ts
This fix updates the Vite build configuration for the injected script (nil.ts) by switching the output format to 'iife' and adding a unique global name. This change ensures the entire bundle is wrapped in an isolated function scope, preventing internal variables from leaking into the page's global context
Fixed https://github.com/NilFoundation/nil/issues/484
> fix: wrap injected script in IIFE to prevent global variable leaks

- nil/internal/network/pubsub_test.go
The pub-sub test is extremely prone to failing in CI, yet often passes locally.
Example: https://github.com/NilFoundation/nil/actions/runs/13705312486/job/38329100031?pr=488
Here I disable the "complex scenario" but keep the code so that it can be run locally if desired.
This way of testing libp2p really makes little sense. At the basic level, libp2p works. Complex cases can only work on a real network anyway.
> [pubsub] Disable flaky test until better solution

- nil/cmd/exporter/internal/clickhouse/scheme.go
- nil/cmd/exporter/internal/exporter.go
- nil/internal/collate/bootstrap.go
- nil/internal/execution/account_state.go
- nil/internal/execution/block_cache.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/state.go
- nil/internal/execution/transient_storage.go
- nil/internal/vm/instructions.go
- nil/services/rpc/filters/filters.go
- nil/services/rpc/jsonrpc/send_transaction.go
- nil/services/rpc/rawapi/local_block.go
- nil/services/synccommittee/prover/tracer/state_db.go
Based on https://github.com/NilFoundation/nil/pull/434#discussion_r1983573480
It was suggested that we should uniformly use `common.EmptyHash` instead of `common.Hash{}`.
Here's the implementation. It only avoids files of geth (they have their own code style).
> [cluster common] Use EmptyHash instead of Hash{}

- explorer_frontend/src/features/contracts/components/Management/Method.tsx
- explorer_frontend/src/features/contracts/init.ts
This PR solves 2 minor issues https://github.com/NilFoundation/nil/issues/452 and https://github.com/NilFoundation/nil/issues/441 which are crucial functionalities to be supported in the playground. It adds support to pure type functions being queryable via the playground as well as the support to input boolean values in inputs.
> fix: support to pure type function and boolean inputs

- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/services/nilservice/service.go
It's possible case that during block replay specific block.mainShardHash
is not available. That shouldn't happen normally since we replay main shard
really fast.
But because of network issues or something else it can be a problem.
So this patch adds simple logic that tries to wait expected block using
subscriptions.
> [collate] add wait main shard block logic to block replay 

- uniswap/tasks/basic/basic.ts
Currently the uniswap tasks fail when `faucetDeposit` key is not set in `.env` and the `.env.example` as well doesn't include any information about this. Removing this check for checking its existence will let the tasks run correctly.
> [uniswap] : fix bug associated with account creation

- explorer_frontend/src/features/account-connector/components/Token.tsx
- explorer_frontend/src/features/tokens/assets/custom.svg
- explorer_frontend/src/features/tokens/utils.ts
We had an issue, were we were not handling custom default tokens on playground wallet, and when someone would add it it would break ux. This PR add fail safe mechanism for properly handling these
This PR does not integrates all custom mock tokens we want, if someone needs new custom tokens, and you want to display them in the wallets, they need to be added (label, icon..)
> fix custom token in playground wallet

- nil/services/cometa/compilation.go
- nil/services/cometa/service_test.go
- nil/services/cometa/tests/Issue465.sol
- nil/services/cometa/tests/issue465.json
In some cases Solidity compiler does not produce generated sources. Cometa did not expect this and therefore failed.
Closes #465
> [cometa] fix compilation bug caused by missing generated files

- nil/common/concurrent/suspendable_test.go
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/block_batch_test.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/testaide/blocks.go
- nil/services/synccommittee/internal/types/block_batch.go
* Introduced parent-child links between block batches (`BlockBatch.ParentId` field). First batch generated by SyncCommittee is expected to have `nil` parent;
* Introduced functionality to track the latest batch ID in `BlockStorage` and link block batches through parent batch IDs;
Links between batches created by SC are required to restore batches sequence during task cancellation process
> Sync Committee: Parent-child batch linking

- nil/internal/execution/zerostate.go
Since token units start from 10^18, we need more liquidity to work with plausible sums. Let's increase the amounts with the margin.
> [GH-#][execution] Increase default balance for default faucets.

- .golangci.yml
- nil/contracts/solidity/tests/TokensTest.sol
- nil/internal/vm/precompiled.go
- nil/tests/multitoken/multitoken_test.go
This patch fixes following issue:
```
../../internal/collate/proposer.go:249 > Transaction execution failed. It doesn't prevent adding it to the block. error="PanicDuringExecution: runtime error: invalid memory address or nil pointer dereference" shardId=[1]	 txnHash=[0x0001d9bb8d922e7078faf8345b41498fc4c6aee8529201124200ba84fafb064c]
```
It was hard to reproduce this issue but anyway it's possible. The reason is that `err` object always was `nil`.
> [vm] fix PanicDuringExecution if contract deployed with tokens

- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
In case if consensus enabled we expect that all validator of non-main shards will be validate main shard as well. This patch extends a bit validation to prevent following cases:
- main shard is not specified in the list of shards
- standalone main shard
> [nilservice] improve validation for validator nodes

- nil/services/rpc/jsonrpc/eth_filters_test.go
Only this part doesn't use waiting for result. All parts above have it. Let's try to make test a bit more stable in that way because sometimes it fails in CI.
> [tests] add retries to filters test

- nil/internal/config/cache.go
- nil/internal/config/params.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/consensus/ibft/validators.go
- nil/internal/consensus/ibft/verifier.go
- nil/internal/signer/block_verifier.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/tests/basic/basic_test.go
- nil/tests/read_through/read_through_db_test.go
This patch introduces an LRU cache for blockchain config. This cache is shared between syncers and validators. It could be useful if the validator gets behind, in which case we switch to the syncer, which can use the cached entries. It is also useful for the validators because we require the same height's config in different places throughout the validation. 
The caching is disabled in sharded suite because otherwise the cache will be shared between instances, but it is enabled in rpc suite.
> [nild] Introduce caching to blockchain config

- Makefile
- nil/cmd/cometa/main.go
- nil/cmd/exporter/main.go
- nil/cmd/nild/devnet.go
- nil/cmd/nild/main.go
- nil/cmd/relay/main.go
- nil/internal/cobrax/cmdflags/network.go
- nil/internal/cobrax/cmdflags/telemetry.go
- nil/internal/cobrax/commands.go
- nil/internal/cobrax/config.go
- nil/internal/cobrax/flags.go
- nil/internal/network/config.go
- nil/internal/network/host.go
- nil/internal/network/keys.go
- nil/internal/network/manager.go
- nil/internal/profiling/profiling.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
https://github.com/NilFoundation/nil/issues/489
The cluster should be available for libp2p connections from the public network (mainly from archive nodes).
Here is the first part of the implementation: adding a relay service.
The service is very basic, and, apart from basic stuff like logging and telemetry, only sets itself up as a libp2p relay service and waits to be killed.
I'm going to test it with cluster nodes that explicitly connect to it as a relay (also, auto-relay feature is implemented in libp2p, but I'm not sure about its feature of advertising relayed nodes). It should be enough for the initial setup.
Next PR will present the working setup.
In order to reduce boilerplate and reuse similar cli interfaces, I've introduced `cobrax` and functions in `telemetry` and `network` that …
> [network] Introduce relay + refactor cmd flags

- nil/contracts/solidity/tests/Test.sol
- nil/internal/execution/state.go
- nil/services/rpc/rawapi/pb/conversion.go
- nil/services/rpc/rawapi/pb/conversion_test.go
- nil/tests/regression/regression_test.go
Faced errors in the cluster log:
```
{
"level": "error",
"component": "network",
"p2pIdentity": "16Uiu2HAmQ62Uh4CaACYPp3Lj9igQmg7F6ciSTszbMUzP238kEpv9",
"protocolId": "/nil/shard/1/rawapi/GetFullBlockData",
"error": "failed to pack Protobuf response: string field contains invalid UTF-8",
"caller": "github.com/NilFoundation/nil/nil/internal/network/manager.go:199",
"time": "2025-03-10T14:48:00Z",
"message": "Failed to handle request"
}
```
> [GH-#] Make sure that the errors are valid UTF-8 strings

- rollup-bridge-contracts/package.json
Fix an error, that cause nil dev deployment to fail:
```
Error: ERROR processing /home/synccom/rollup-bridge-contracts/deploy/deploy-contracts.ts:
Error: invalid object key - customData (argument="transaction:customData", value={"gasLimit":100232,"nonce":0,"data":"0x6080806040523460135760d4908160188239f35b5f80fdfe6080604052600436
```
> fix error invalid object key - customData

- nil/tests/basic/basic_test.go
- nil/tests/regression/regression_test.go
- nil/tests/rpc_service/rpc_service_test.go
Currently basic test suite consumes around 10 minutes in our CI. Some tests were independent and they only read some data from HTTP API.
I moved this tests into separate suite called "rpc service". It runs nilservice only once with disabled consensus.
> [tests] move read-only tests from basic test suite

- nil/services/nil_load_generator/service.go
Before this patch logs looked in a following way:
```
User: 0, Pair: 2, AmountSend: [10000 0 0 0],  AmountGet: 3
```
We expect to have here some reasonable number instead of array of 4 * uint64. This patch should fix it.
> [loadgen] fix bad logging of uint256

- nil/cmd/nild/devnet.go
- nil/contracts/solidity/system/Governance.sol
- nil/internal/collate/proposer.go
- nil/internal/config/generate.go
- nil/internal/contracts/contract.go
- nil/internal/crypto/secp256k1.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/proposal.go
- nil/internal/execution/state.go
- nil/internal/execution/zerostate.go
- nil/internal/types/address.go
- nil/internal/types/block.go
- nil/internal/types/exec_errors.go
- nil/internal/types/ssz_test.go
- nil/internal/vm/evm.go
- nil/internal/vm/interface.go
- nil/internal/vm/precompiled.go
- nil/services/cliservice/block_format_test.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/synccommittee/prover/tracer/state_db.go
- nil/tests/governance/rollback_test.go
- nil/tests/rpc_suite.go
- smart-contracts/contracts/Nil.sol
- smart-contracts/contracts/SmartAccount.sol
During network launch, we may encounter misconfigurations, vulnerabilities or bugs in the validators or the provers that may result in malicious or breaking changes to the state of the blockchain. One way to deal with them at early stages of the mainnet is "rolling back" to a known good state when an authority decides to do so.
This patch adds a "governance" system contract on the main shard and a corresponding precompile, accepting rollback transactions signed by a "sudo key" (currently the same as the "main key" of the built-in system smart account). The rollback functionality itself will be implemented by following patches.
> Add a "governance" system contract that will be able to initiate rollbacks

- explorer_frontend/src/features/code/Code.tsx
- explorer_frontend/src/features/code/hooks/useCompileButton.tsx
closes #167 
As described in the #167, currently we have a problem with compile hotkey (`meta+enter` or `cmd+enter`) when user focuses code field.
This diff adds keymap extension that allows to define custom keyboard shortcuts (key bindings). By setting `run: () => true,` we prevent any action on the code field. At the same time we run `compile()` event avoiding adding extra symbols to the code.
We need to use `Prec.highest()` because the extension should always go first in the extensions list.
> [playground] fix compile hotkey combo adds extra symbol to the code

- nil/internal/telemetry/internal/config.go
- nil/internal/telemetry/internal/metric.go
That can be very useful for local setup when signoz collector works inside docker but nild instaces run inside Vagrant.
> [telemetry] allow to specify endpoint for metrics

- nil/cmd/nild/main.go
- nil/internal/db/badger.go
- nil/services/nilservice/config.go
The configs are regenerated each deploy anyway, so no need to keep compatibility.
> [config] Remove legacy flags networkKeysPath and db.allowDrop

- nil/services/synccommittee/core/service_test.go
- nil/services/synccommittee/prover/tracer/tracer_nild_test.go
For some reasons we see following failures in CI:
```
2025-03-11T08:47:24.4638935Z nil> 2025-03-11 08:47:09 DBG [consensus]         ../../../../go-ibft/core/ibft.go:444 > block proposal accepted shardId=[1]
2025-03-11T08:47:24.4639316Z nil> 2025-03-11 08:47:09 DBG [consensus]         ../../../../go-ibft/core/ibft.go:448 > pre-prepare message multicasted shardId=[2]
2025-03-11T08:47:24.4639642Z nil> 2025-03-11 08:47:09 DBG [consensus]         ../../../../go-ibft/core/ibft.go:840 > enter: prepare state shardId=[2]
2025-03-11T08:47:24.4639763Z nil> signal: killed
2025-03-11T08:47:24.4640119Z nil> FAIL       github.com/NilFoundation/nil/nil/services/synccommittee/prover/tracer   232.386s
2025-03-11T08:47:24.4640588Z nil> ok         github.com/NilFoundation/nil/nil/services/synccommittee/prover …
```
> [tests] disable consensus for synccommittee test to prevent CI failures

- nil/client/client.go
- nil/client/direct_client.go
- nil/client/rpc/client.go
- nil/client/web3_client.go
- nil/common/version/version.go
- nil/services/nilservice/service.go
- nil/services/rpc/jsonrpc/web3_api.go
- nil/services/rpc/rawapi/api.go
- nil/services/rpc/rawapi/client.go
- nil/services/rpc/rawapi/local_web3.go
- nil/services/rpc/rawapi/node.go
- nil/services/rpc/rawapi/pb/conversion.go
- nil/services/rpc/rawapi/proto/common.proto
- nil/services/rpc/rawapi/server.go
- nil/tests/rpc_service/rpc_service_test.go
After this patch it will be possible to retrieve a version of current validator node.
Closes #541
> [jsonrpc] implement web3_clientVersion

- nil/internal/execution/account_state.go
- nil/internal/execution/state.go
- nil/internal/vm/evm.go
- nil/tests/regression/regression_test.go
- Decoding message from return data must be performed only for `ErrExecutionReverted` errors.
- Enable deploying to accounts with `seqno` != 0. Because even failed transactions are incrementing it. 
- Do not save non-existent values read at the time of execution to StateTree. It has a drawback that non-existing values are not cached now, but if we cache them, then they will be written to the state and change it even if there were no `SSTORE` instruction. Here is a ticket on this issue #546.
Closes #543
> Fix decoding of revert messages and deploy transactions

- nil/cmd/prover/main.go
- nil/cmd/sync_committee/main.go
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/aggregator_test.go
- nil/services/synccommittee/core/block_batch_test.go
- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/internal/types/block_batch.go
- nil/services/synccommittee/internal/types/prover_tasks.go
- nil/services/synccommittee/internal/types/task_type.go
- nil/services/synccommittee/proofprovider/task_handler.go
- nil/services/synccommittee/proofprovider/task_handler_test.go
- nil/services/synccommittee/proofprovider/task_state_change_handler.go
- nil/services/synccommittee/prover/commands/command_factory.go
- nil/services/synccommittee/prover/commands/partial_proof.go
- nil/services/synccommittee/prover/task_handler.go
- nil/services/synccommittee/prover/tracer/state_db.go
- nil/services/synccommittee/prover/tracer/tracer.go
- Handle proof batch of blocks as single task on proof-provider level
- Add option "disable-l1" for sync committee
- `Task`: add `BlockIds`, `ShardIds`
- tracer `Config`: add `ShardIDs`
Collect traces for blocks from different shards
> Sync Committee: Proof batch in single task

- explorer_backend/services/sqlite.ts
- flake.nix
- nil/cmd/exporter/internal/exporter.go
- nix/container.nix
- nix/nilexplorer.nix
This PR when merged will allow you to run cluster setup almost exactly like it does in production, in a matter of seconds. The word "container" here may be a bit misleading, because even though we do start a cgroup, it will run systemd, nild, nginx, and other things like a normal operating system (and unlike Docker for example).
Note, that you need NixOS installed and not just Nix package manager, because the `nixos-container` tool is not available with just Nix.
```
sudo nixos-container create devcontainer --flake .
sudo nixos-container start devcontainer
```
If you made changes to nild or configs and want to update the container in-place, you can do:
```
sudo nixos-container update devcontainer --flake .
```
As a follow-up, I will add ClickHouse, exporter, and all frontend parts to run …
> Add a nixos container that can run full cluster

- go.mod
- go.sum
- nil/cmd/relay/main.go
- nil/internal/db/badger.go
- nil/internal/db/datastore.go
- nil/internal/db/datastore_test.go
- nil/internal/db/tables.go
- nil/internal/network/dht.go
- nil/internal/network/manager.go
- nil/internal/network/manager_test.go
- nil/internal/network/testaide.go
- nil/services/nilservice/service.go
- nil/tests/detectrace/detectrace.go
- nil/tests/detectrace/no_race.go
- nil/tests/detectrace/race.go
- nix/nil.nix
This patch adds a DHT datastore, which aims to make the network more stable and allow nodes to survive restarts more reliably.
Originally, all the code was taken from github.com/ipfs/go-ds-badger4. However, since we use Badger as the primary storage, there is no reason to open a separate database. To prevent mixing blockchain data with DHT data, table functionality was introduced. Everything continues to work as expected since we use an external test suite.
> [network] add datastore for DHT

- nil/internal/telemetry/telemetry.go
Right now all our instances has `/usr/bin/nild` as a service name. After this patch it should be `nil-0`, ..., `nil-N`, `nil-rpc-0`,...
> [telemetry] report OTEL_SERVICE_NAME as a service name if it's provided

- nil/cmd/exporter/internal/clickhouse/clickhouse.go
- nil/services/cliservice/faucet.go
These changes are the result of devnet debugging:
- Exporter can't start due to panic with wrong receipt's output transactions.
- Increasing faucet timings will probably help to cope with a significant load on the rpc-node.
> Adjust faucet timings and fix exporter

- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/aggregator_test.go
- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/reset/resetter.go
- nil/services/synccommittee/core/reset/state_reset_launcher.go
- nil/services/synccommittee/core/task_state_change_handler.go
- nil/services/synccommittee/internal/metrics/sync_committee_metrics.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/storage/errors.go
- nil/services/synccommittee/internal/types/block_batch.go
- nil/services/synccommittee/internal/types/blocks.go
- nil/services/synccommittee/internal/types/errors.go
This update replaces block-level operations with batch-level processing across the Sync Committee services to:
- Simplify task cancellation logic.
- Support the new multi-block batching model.
- Introduced `batchEntry` struct to hold references to blocks, stored in a new dedicated table.
- Removed the `IsProved` field from `blockEntry`; it is now associated with the batch.
- Replaced `SetBlockAsProved(BlockId)` with `SetBatchAsProved(BatchId)`.
- Updated `TryGetNextProposalData()` to use the main shard block hash as the state root instead of `ChildBlocksRootHash`.
- Replaced `SetBlockAsProposed(BlockId)` with `SetBatchAsProposed(BatchId)`.
- The starting point is now determined by `BatchId` instead of the main shard block hash.
- Switched from block-based iteration to a mechanism using …
> Sync Committee: Transition to Batch-Level Operations

- nil/internal/collate/validator.go
Seems it's possible case when we write two notify messages into a channel before wait code call unsubscribe. Let's skip channels that don't accept messages.
> [collate] fix deadlock on block subscription

- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/aggregator_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/proposer_test.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/core/task_state_change_handler.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/types/blocks.go
- nil/services/synccommittee/prover/tracer/state_db.go
- Return initialization of latest proved state root back to `proposer`
- If `Nil RollUp` contract not accessible - set hash of genesis block from main shard
- Add RPC client to `proposer`
- Fix processing result of `ProofBatch` tasks
> Sync committee: Fix initialization last proved state root

- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_entries.go
- nil/services/synccommittee/internal/storage/block_storage_op_batch.go
- nil/services/synccommittee/internal/storage/block_storage_op_batch_count.go
- nil/services/synccommittee/internal/storage/block_storage_op_batch_latest.go
- nil/services/synccommittee/internal/storage/block_storage_op_block.go
- nil/services/synccommittee/internal/storage/block_storage_op_blocks_latest_fetched.go
- nil/services/synccommittee/internal/storage/block_storage_op_state_root.go
* Introduced separate types (`batchOp`, `batchCountOp`, `stateRootOp`, etc.) to represent isolated sets of operations on different data structures: blocks, batches, secondary indices, etc;
* Reduced the size of `block_storage.go` file from ~1100 lines to ~600;
* No functional changes introduced
> Sync Committee: Block Storage Refactoring

- nil/internal/telemetry/telattr/attributes.go
- nil/services/rpc/transport/handler.go
- nil/services/rpc/transport/server.go
This patch adds duration/count metrics to JSON RPC request handler.
> [rpc] add metrics to rpc request handler

- explorer_backend/daos/blocks.ts
- nil/cmd/exporter/internal/clickhouse/clickhouse.go
- nil/internal/types/block.go
- nil/internal/types/transaction.go
Closes #469 
Changes:
- Changed clickhouse column name to `out_txn_num` in `BlockData.OutTransactionsNum` in file `internal/types/block.go` to match with `BlockWithBinary.OutTxnNum` in `clickhouse.go`
- converted from camelcase ch names to snake case in `internal/types/transaction.go`
This PR was originally authored by @varun-doshi in #582.
> improved clickhouse columns

- Makefile
- nil/Makefile.inc
- nil/cmd/relayer/main.go
- nil/internal/db/badger.go
- nil/internal/db/kv.go
- nil/internal/readthroughdb/read_through.go
- nil/services/relayer/internal/l1/contract_wrapper.go
- nil/services/relayer/internal/l1/errors.go
- nil/services/relayer/internal/l1/eth_client.go
- nil/services/relayer/internal/l1/event_listener.go
- nil/services/relayer/internal/l1/event_listener_test.go
- nil/services/relayer/internal/l1/finality_ensurer.go
- nil/services/relayer/internal/l1/generate.go
- nil/services/relayer/internal/l1/l1_bridge_messenger_abi.json
- nil/services/relayer/internal/l1/storage.go
- nil/services/relayer/internal/l1/types.go
- nil/services/relayer/internal/l2/transaction_sender.go
- nil/services/relayer/service.go
**For scared ones**: 1.5k LoC of changes here are just .abi.json content for the L1BridgeMessenger contract that should be generated automatically in future :)
This PR adds an initial version of the relayer service. 
By spec the service is responsible for:
- Fetching ongoing and historical events from the L1BridgeMessenger contract deployed to the L1 (`EventListener` component)
- Monitoring L1 block finalization (`FinalityEnsurer` component)
- Signing and forwarding finalized L1 events to the L2 (`TransactionSender` component)
Initial version of the service is a `sync_committee_relayer` binary with `EventListener` component implementation
Here is brief description of the component functionality:
- Connect to L1
- Check which historical events has to be fetched (based on stored last …
> relayer: event listener impl

- explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
- explorer_frontend/src/features/tutorial/assets/tutorialTwo/tutorialTwoContracts.sol
This diff fixes the check for the second tutorial by capping `feeCredit` and adding a proper `receive()` function.
> [playground] fixed second tutorial

- nil/cmd/cometa/main.go
It should be persistent since we start cometa with `cometa run ...` command. Here `run` is a subcommand and log-level flag should be persistent.
> [cometa] fix --log-level flag usage

- nil/cmd/sync_committee_cli/internal/commands/task_fields.go
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/block_batch_test.go
- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/internal/log/events.go
- nil/services/synccommittee/internal/rpc/task_debug_rpc_test.go
- nil/services/synccommittee/internal/rpc/task_request_handler_rpc_suite_test.go
- nil/services/synccommittee/internal/storage/task_storage_test.go
- nil/services/synccommittee/internal/testaide/prover_tasks.go
- nil/services/synccommittee/internal/types/block_batch.go
- nil/services/synccommittee/internal/types/prover_tasks.go
- nil/services/synccommittee/internal/types/task_type.go
- nil/services/synccommittee/proofprovider/task_handler.go
- nil/services/synccommittee/proofprovider/task_handler_test.go
- nil/services/synccommittee/prover/commands/aggregate_challenges.go
- nil/services/synccommittee/prover/commands/aggregate_fri.go
- nil/services/synccommittee/prover/commands/aggregate_proof.go
- nil/services/synccommittee/prover/commands/combined_q.go
- nil/services/synccommittee/prover/commands/command_factory.go
- nil/services/synccommittee/prover/commands/consistency_check.go
- nil/services/synccommittee/prover/commands/merge_proof.go
- nil/services/synccommittee/prover/commands/partial_proof.go
- nil/services/synccommittee/public/task_view.go
The updated pipeline for generating proofs now omits the aggregation step, block proofs are replaced with a single batch proof.
Updated Task Pipeline:
1. SyncCommittee: Initiates a task to prove the batch.
2. Proof-provider processes the following DFRI tasks:
- Partial proofs.
- Generation of aggregated challenges.
- Computation of combined Q.
- Aggregation of FRI.
- Execution of consistency checks.
- Merging of proofs.
3. The resulting merged proof, along with the public input, is returned to the SyncCommittee as a binary task result, serving as the proof of the batch.
> feat(synccommittee): rework task pipeline, block proofs -> batch proof

- nil/internal/execution/state.go
Probably it was lost during refactoring.
> [execution] drop unused variable

- docs_ai_backend/tsconfig.json
We can not build `docs_ai_backend` because of the error `Type error: Cannot find type definition file for 'hapi__shot'`. It's not clear why the error appeared, but i bet it is again because of `package-lock.json` issues.
Anyway, this diff introduces a simple fix - implicit type reference in `tsconfig.json`.
> [docs] fix docs_ai_back build by adjusting typescript config

- flake.nix
Default gzip doesn't support parallel compression while xz does. On my own laptop results of building deb with only nil binaries:
gzip (3 min) vs xz (2:30 min).
That's very important and useful when you debug something on dev/local stand.
Also size after compression is important. Here xz also wins: 470mb (gzip) vs 315 (xz).
> [build] change deb compression to xz

- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/aggregator_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/internal/testaide/blocks.go
- nil/services/synccommittee/internal/types/blocks.go
- nil/services/synccommittee/internal/types/errors.go
To align with state root initialization on the `Proposer` side, the latest proved state root (or genesis block) is used as a starting point in the Aggregator as well.
* Implemented the `getStartingBlockRef()` method, which retrieves the starting point for the next fetching iteration, prioritizing the latest fetched block if available;
* If neither `LatestFetched` nor `LatestProvedStateRoot` is defined, the method returns `ErrStateRootNotInitialized`;
* Added a check to verify whether the `LatestFetched` block exists on L2, triggering a reset if it does not (`requireBlockExistsInChain`);
In short, `LatestProvedStateRoot` must now be initialized to be used by `Aggregator` as the starting point for block processing
> Sync Committee: Initial Batch Construction

- nil/services/rpc/internal/http/connection.go
This diff downgrades minimum supported niljs version to 0.24.0
> [release] downgrade supported niljs version to 0.24.0

- Makefile
- nil/internal/collate/errors/errors.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/consensus/ibft/verifier.go
This patch adds more logs to consensus. E.g. in case of IsValidProposalHash failure. Also this patch fixes annoying "Failed to insert proposal" errors in case of OldBlock error.
> [consensus] add more logs in case of errors

- nil/services/txnpool/tree.go
- nil/services/txnpool/txnpool.go
Data race was in accessing `baseFee` field in the `TxnPool`.
> [txpool] Fix data race in txpool

- flake.nix
- nix/npmdeps.nix
- nix/rollup-bridge-contracts.nix
- package-lock.json
- rollup-bridge-contracts/.gitignore
- rollup-bridge-contracts/contracts/NilAccessControl.sol
- rollup-bridge-contracts/contracts/NilRollup.sol
- rollup-bridge-contracts/contracts/interfaces/INilAccessControl.sol
- rollup-bridge-contracts/contracts/interfaces/INilRollup.sol
- rollup-bridge-contracts/contracts/interfaces/INilVerifier.sol
- rollup-bridge-contracts/contracts/verifier/NilVerifier.sol
- rollup-bridge-contracts/forge_command_proxy.sh
- rollup-bridge-contracts/foundry.toml
- rollup-bridge-contracts/hardhat.config.ts
- rollup-bridge-contracts/package.json
- rollup-bridge-contracts/remappings.txt
- rollup-bridge-contracts/test/BaseTest.sol
- rollup-bridge-contracts/test/NilRollup.t.sol
- rollup-bridge-contracts/test/NilRollupAccessControl.t.sol
- rollup-bridge-contracts/test/misc/CustomTransparentUpgradeableProxy.sol
- rollup-bridge-contracts/test/misc/EmptyContract.sol
- rollup-bridge-contracts/test/mocks/NilRollupMockBlob.sol
- rollup-bridge-contracts/test/mocks/NilRollupMockBlobInvalidScenario.sol
Add forge unittests in rollup-bridge-contracts/
> Add unittests in rollup-bridge-contracts/

- Makefile
- nil/cmd/exporter/internal/clickhouse/clickhouse.go
- nil/internal/execution/state.go
- nix/nil.nix
- Remove unnecessary receipts map because the receipt is placed in the same index as the corresponding transaction.
- Set tag `assert` by default for all binaries. ~~Add an additional check that the transaction is always unique in the database.~~
> [exporter, execution] Small improve in exporter, enable `assert` tags by default

- nil/internal/collate/proposer.go
- nil/internal/collate/validator.go
- nil/internal/types/block.go
- nil/services/synccommittee/prover/tracer/tracer_mock_client_test.go
In case of difference in config roots let's dump all config content to be able to debug problematic value. In logic below we dump all block header but it's not enough to see only that two hashes is different.
> [collate] make validator more verbose

- nil/services/rpc/unix_socket.go
- nil/services/rpc/unix_socket_test.go
We trim the paths so that we don't run into the socket path length limitation. Since `MkdirTemp` adds a random number to the suffix anyway, this is safe.
> [GH-#] GetSockPath* fixed for tests with long names

- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/validator.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/consensus/ibft/messages.go
- nil/internal/consensus/ibft/verifier.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/contract_test.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/postprocess.go
- nil/internal/execution/state.go
- nil/internal/execution/testaide.go
- nil/internal/execution/zerostate_test.go
- nil/internal/vm/precompiled.go
- nil/services/rpc/filters/filters_test.go
- nil/services/rpc/jsonrpc/debug_api_test.go
- nil/services/rpc/jsonrpc/eth_accounts_test.go
- nil/services/rpc/jsonrpc/eth_receipt_test.go
- nil/services/rpc/jsonrpc/eth_transaction_test.go
During the replay block, we do not update the collator state, which may cause the proposer to include transactions that have already been executed.
This patch adds a check to detect already executed transactions — such messages will now be skipped.
> [collate] workaround doubled tx

- nil/common/logging/fields.go
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/aggregator_test.go
- nil/services/synccommittee/core/batches/encode/v1/encoder_test.go
- nil/services/synccommittee/core/batches/encode/v1/serialization.go
- nil/services/synccommittee/core/block_batch_test.go
- nil/services/synccommittee/core/block_fetcher.go
- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/service_test.go
- nil/services/synccommittee/core/subgraph_fetcher.go
- nil/services/synccommittee/core/subgraph_fetcher_test.go
- nil/services/synccommittee/internal/metrics/sync_committee_metrics.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_entries.go
- nil/services/synccommittee/internal/storage/block_storage_op_batch.go
- nil/services/synccommittee/internal/storage/block_storage_op_blocks_latest_fetched.go
- nil/services/synccommittee/internal/storage/block_storage_op_state_root.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/testaide/blocks.go
- nil/services/synccommittee/internal/testaide/client_mock_block_setter.go
- nil/services/synccommittee/internal/types/block_batch.go
- nil/services/synccommittee/internal/types/block_subgraph.go
- nil/services/synccommittee/internal/types/blocks.go
- nil/services/synccommittee/internal/types/prover_tasks.go
- nil/services/synccommittee/proofprovider/task_handler_test.go
* Declared a new `Subgraph` type representing a dedicated subset of blocks, with the main shard block as the root;
* Updated the `BlockBatch` type to include multiple sequential subgraphs;
* Extended the `BlockBatch` exported API to simplify block traversal;
* Updated the `blockEntry` type to align with the modified `BlockBatch`;
* `BlockStorage.GetLatestFetched()` now returns `BlockRefs` — a map instead of a single main reference;  
* Reimplemented methods in `block_storage_op_blocks_latest_fetched.go` to support multi-shard tracking of fetched references;  
* Removed the `ParentId` secondary index (methods: `putBatchParentIndexEntry` and `deleteBatchParentIndexEntry`; table: `blocks_parent_hash_idx`);  
* During a partial reset, batches are now traversed in reverse order, starting from …
> Sync Committee: Subgraph Batching

- .github/workflows/build_artifacts.yml
- .golangci.yml
- .vscode/settings.json
- Makefile
- nil/cmd/exporter/internal/exporter.go
- nil/cmd/nil_block_generator/internal/commands/client.go
- nil/cmd/nild/main.go
- nil/common/concurrent/synctest_import_lint_workaround.go
- nil/common/concurrent/utils.go
- nil/common/concurrent/utils_test.go
- nil/services/nilservice/service.go
- nix/nil.nix
In this PR, two changes related to `concurrent.RunWithTimeout`:
1. Instead of panicking, we cancel the current context that the other functions are running with and return the original error from the entire function. This is needed to be able to occasionally terminate with an error, right now we only know how to crash.
3. We keep track of where the function that ended with the error was created. This is very useful for debugging, because unlike panic (inside a function) when an error occurs, we have no way to reliably trace the source of the problem. I think that overhead is not terrible here, because we only create long-lived functions once at the start of services, and do not do it all the time.
> [GH-#] Error handling in RunWithTimeout

- nil/client/client.go
- nil/client/direct_client.go
- nil/client/rpc/client.go
- nil/cmd/nild/main.go
- nil/cmd/stresser/main.go
- nil/internal/execution/state.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/services/rpc/jsonrpc/debug_api_test.go
- nil/services/rpc/jsonrpc/dev_api.go
- nil/services/rpc/jsonrpc/eth_api_test.go
- nil/services/rpc/rawapi/api.go
- nil/services/rpc/rawapi/client.go
- nil/services/rpc/rawapi/local.go
- nil/services/rpc/rawapi/local_dev.go
- nil/services/rpc/rawapi/node.go
- nil/services/rpc/rawapi/server.go
- nil/services/stresser/core/helper.go
- nil/services/stresser/examples/workload.yaml
- nil/services/stresser/instance.go
- nil/services/stresser/stresser.go
- nil/services/stresser/workload/do_panic.go
- nil/services/stresser/workload/runner.go
- nil/services/stresser/workload/workload.go
- nil/services/txnpool/txnpool.go
- nil/tests/rpc_suite.go
`DEVAPI` is an api for utilities useful for developers. Currently, it contains only one method `DoPanicOnShard` which forces validator, which is currently being used for the given shard, to crash.
Also, there are some improvements in Stresser:
- Add `do_panic` workload.
- Add retries for top-up via Faucet. It is necessary because of a known issue with data race of Faucet contract's seqno.
- Improve the procedure of waiting for cluster readiness.
> [rpc, stresser] Introduce dev-api with `DoPanicOnShard` method

- nil/contracts/solidity/tests/Test.sol
- nil/internal/collate/proposer_test.go
- nil/internal/execution/state.go
- nil/tests/cli/cli_test.go
- nil/tests/regression/regression_test.go
We authorized such message that mean that user paid for it. However in case if we don't increment seqno it's possible to send two transactions with the same hash that will be processed and create hash collision.
> [execution] inc seqno on errors with a balance

- nil/cmd/nil/internal/block/block.go
- nil/internal/execution/postprocess.go
- nil/services/cliservice/block.go
- nil/services/cliservice/block_format_test.go
- nil/tests/cli/cli_test.go
Before this patch simple request could crash CLI:
```
nil block 0x0004c3c56fde2450c25c9f0501588655be1483e083014f0e6ad4fa617c68432b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x125a4be]
goroutine 1 [running]:
github.com/NilFoundation/nil/nil/services/rpc/jsonrpc.(*DebugRPCBlock).Decode(0x0)
github.com/NilFoundation/nil/nil/services/rpc/jsonrpc/types.go:182 +0x3e
github.com/NilFoundation/nil/nil/services/rpc/jsonrpc.(*DebugRPCBlock).DecodeSSZ(0xc000312000?)
github.com/NilFoundation/nil/nil/services/rpc/jsonrpc/types.go:199 +0x13
github.com/NilFoundation/nil/nil/services/cliservice.(*Service).FetchDebugBlock(0xc00048c460, 0x1, {0x16cada0?, 0xc0004742e0?}, 0x0, 0x0, 0x0) …
```
> [cli] fix crash on requesting non-existing block 

- nil/cmd/journald_forwarder/main.go
- nil/services/journald_forwarder/main.go
Don't send logs when we fetch log. Over wise we get loop.
> [journald-forwarder] Stop sending logs from journald forwarder, when we fetch logs

- .github/pull_request_template.md
This PR introduces a template for pull requests which should help external contributors for opening a PR. It includes a short format for what the PR can contain and also some checklists which are essential for following our guidelines.
> Added PR template for external contributors

- nil/Makefile.inc
- nil/cmd/relayer/main.go
- nil/services/relayer/internal/l1/finality_ensurer.go
- nil/services/relayer/internal/l2/contract_wrapper.go
- nil/services/relayer/internal/l2/generate.go
- nil/services/relayer/internal/l2/l2_bridge_messenger_abi.json
- nil/services/relayer/internal/l2/transaction_sender.go
- nil/services/relayer/internal/l2/transaction_sender_test.go
- nil/services/relayer/service.go
Implementation of relayer `TransactionSender` component
This component is responsible for:
- Fetching event from L2 storage
- Ordered forwarding of the events to the L2
- Dropping events from L2 storage
PR also contains L2 contract wrapper which provides an interface to interact with `L2BridgeMessenger` contract and some initial config for it (nil RPC endpoint, contract/account address, key). Current version only generates the key (if it is not exists). Other initialization stuff is going to be implemented in the following PRs
> relayer: transaction sender impl

- nil/cmd/proof_provider/main.go
- nil/services/synccommittee/internal/api/task_handler.go
- nil/services/synccommittee/internal/executor/task_executor.go
- nil/services/synccommittee/internal/executor/task_executor_test.go
- nil/services/synccommittee/proofprovider/service.go
- nil/services/synccommittee/proofprovider/task_handler.go
- nil/services/synccommittee/proofprovider/task_handler_test.go
- nil/services/synccommittee/prover/task_handler.go
Currently proof provider fetches new batch tasks regardless of number of prover tasks in the queue. This commit introduces a limit for the queue.
> Limit number of tasks for proof provider

- nil/services/relayer/internal/l1/event_listener.go
- nil/services/relayer/internal/l1/event_listener_test.go
- nil/services/relayer/internal/l1/finality_ensurer.go
- nil/services/relayer/internal/l1/finality_ensurer_test.go
- nil/services/relayer/internal/l1/metrics.go
- nil/services/relayer/internal/l1/storage.go
- nil/services/relayer/internal/l2/metrics.go
- nil/services/relayer/internal/l2/storage.go
- nil/services/relayer/internal/l2/transaction_sender.go
- nil/services/relayer/internal/l2/transaction_sender_test.go
- nil/services/relayer/internal/metrics/init.go
- nil/services/relayer/internal/storage/json_writer.go
- nil/services/relayer/internal/storage/metrics.go
- nil/services/relayer/internal/storage/storage.go
- nil/services/relayer/service.go
This PR adds metrics needed for monitoring state of the nil relayer service components
Added the following metrics:
- Common DB metrics (collection size, inserts, deletes)
- Event listener metrics (fetcher status, amount of incoming events, errors)
- Finality ensurer metrics (lag of updating finalized block value, amount of finalized & orphaned events)
- Transaction sender (relay/error count)
> relayer metrics

- create-nil-hardhat-project/README.MD
- docs/README.md
- smart-contracts/README.md
This diff corrects three README files so they point to correct licences if applicable. The contribution was made by @donatik27.
- Changed `create-hardhard-project` README to point to the correct licence file
- Changed docs README to the correct licence file
- Removed licence information from `smart-contracts` README
Addresses #707 
> [misc] corrected licence files in READMEs

- explorer_frontend/biome.json
- explorer_frontend/src/features/account-connector/components/RpcUrlScreen.tsx
- explorer_frontend/src/features/account-connector/init.ts
- explorer_frontend/src/features/account-connector/model.ts
- explorer_frontend/src/features/account-connector/validation.ts
This diff contains two changes:
- Validation of the rpc url is removed. The reason behind that is that validation was too strict and user was not able to develop playground locally. 
- Rpc url is now set only after successful wallet creation. It's kinda obvious - there is no need in rpc url if you don't have a wallet. There was a buggy scenario when user tries to create a wallet with some rpc url, which passed validation, but request is not successful. In that case rpc url is going to be set without wallet creation and user is going to receive message "Something wrong with the network" every time the page is open.
> [playground] remove rpcUrl validation

- nil/services/rpc/rawapi/local.go
- nil/services/rpc/rawapi/local_receipt.go
It is a valid situation, in which case the status should be equal to `BaseFeeTooHigh`.
> [rpc] Do not return error if effective priority fee calculation failed

- nil/services/synccommittee/core/reset/resetter.go
- nil/services/synccommittee/core/task_state_change_handler.go
- nil/services/synccommittee/core/task_state_change_handler_test.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
Follow-up #697:
* Do not trigger state reset if batch associated with the task does not exist;
* Extended `TaskStateChangeHandlerTestSuite` with more tests;
> Sync Committee: ProofBatch Task Result Handling

- nil/cmd/nild/main.go
- nil/internal/collate/scheduler.go
It's possible that consensus is interrupted by syner if it committed more fresh block than consensus height. But it's quite interesting to be able to compare consensus height and block number. This patch adds such info.
> [collate] add block number to log message

- nil/cmd/relayer/main.go
- nil/services/cliservice/faucet.go
- nil/services/relayer/internal/l2/contract_wrapper.go
- nil/services/relayer/internal/l2/init.go
- nil/services/relayer/internal/l2/utils.go
- nil/services/relayer/service.go
This PR adds support for debug relayer CLI options
- Now with l2-debug CLI options salt and faucet service endpoint can be passed to service. It will try to automatically create smart account in nild in that case
> relayer debug: add smart account creation

- nil/tests/sharded_suite.go
Because of working goroutine we had race condition in the code. This patch tries to fix it. Stacktrace was following:
```
2025-04-01T13:07:32.6077719Z nil> ==================
2025-04-01T13:07:32.6077836Z nil> WARNING: DATA RACE
2025-04-01T13:07:32.6077970Z nil> Write at 0x00c0004024d0 by goroutine 28:
2025-04-01T13:07:32.6078141Z nil>   github.com/stretchr/testify/suite.(*Suite).SetT()
2025-04-01T13:07:32.6078428Z nil>       /build/source/vendor/github.com/stretchr/testify/suite/suite.go:46 +0x136
2025-04-01T13:07:32.6078593Z nil>   github.com/stretchr/testify/suite.Run.func1.1()
2025-04-01T13:07:32.6078879Z nil>       /build/source/vendor/github.com/stretchr/testify/suite/suite.go:187 +0x347
2025-04-01T13:07:32.6078994Z nil>   runtime.deferreturn()
2025-04-01T13:07:32.6079398Z nil> …
```
> [tests] fix race in TestRpcNode

- Makefile
Building in release mode `make MODE=release` assert tag is not passed. Thus, we avoid the overhead of debugging checks.
> Add release mode to Makefile

- nil/cmd/proof_provider/main.go
- nil/cmd/prover/main.go
- nil/cmd/sync_committee/main.go
- nil/services/synccommittee/core/aggregator.go
- nil/services/synccommittee/core/config.go
- nil/services/synccommittee/internal/rollupcontract/wrapper.go
- nil/services/synccommittee/proofprovider/service.go
- nil/services/synccommittee/prover/service.go
Currently we pass some secret data via cmd options which is insecure. This commit introduces a possibility to read the same options from config files also. It still keeps all the flags, and in case of two values passed from both a config and an option, the option value will be used.
> Support config files for sync_committee binaries

- nil/cmd/exporter/internal/clickhouse/clickhouse.go
- nil/cmd/exporter/internal/clickhouse/clickhouse_test.go
- nil/common/clickhouse.go
- nil/services/cometa/clickhouse.go
- nil/tests/cometa/cometa_test.go
currently Cometa and Exporter fail if particular ClickHouse DB doesn't exist. however they may simply create it in this case
during debugging I encountered a nasty issue with CH processes not being killed properly and hence causing different side effects (such as connecting to old CH server, etc)
> autocreate ClickHouse db if not exists

- docs_ai_backend/next.config.js
- docs_ai_backend/package.json
- docs_ai_backend/src/utils/populateDB.js
- nix/docsaibackend.nix
It looks like it's not very difficult to bundle all necessary npm dependencies together with the docs_ai_backend. What is needed is just to specify `output: standalone` in the next.js config.
I've tried to start the server with `node` from the resulting build and it worked. However, I can't do any in-depth testing and will wait for Shukhrat to do that part.
Part of #728
It is possible that I didn't ship everything that is needed in the resulting distribution, so help is needed.
> Bundle docs_ai_backend

- nil/client/direct_client.go
- nil/internal/contracts/testaide.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/state.go
- nil/services/synccommittee/internal/rpc/task_debug_rpc_test.go
- nil/tests/async_await/async_await_test.go
- nil/tests/common.go
- nil/tests/contracts/Unconstructable.sol
- nil/tests/regression/regression_test.go
- nil/tests/rpc_suite.go
- nil/tests/sharded_suite.go
The previous patch
(cbed7489a815956487b913a4d6ea96922e3ff28d) fixed the possibility of adding identical transactions to
multiple blocks. However, it introduced a regression.
Transactions that are not included in a block (and create so-called temporary receipts) could still
modify the state. This breaks replay, since the
account cannot be brought to the correct state
without that transaction.
This patch fixes the issue by rolling back ExtSeqno if the transaction is not included in a block.
This mainly affects deploy transactions. For
execution transactions, gas is paid if
`verifyExternal` succeeds, so state changes are valid in that case.
> [execution] don't inc ExtSeqno in case if tx is not included to block

- nil/services/synccommittee/core/config.go
- nil/services/synccommittee/core/fetching/aggregator.go
- nil/services/synccommittee/core/fetching/aggregator_test.go
- nil/services/synccommittee/core/fetching/block_fetcher.go
- nil/services/synccommittee/core/fetching/lag_tracker.go
- nil/services/synccommittee/core/fetching/lag_tracker_test.go
- nil/services/synccommittee/core/fetching/subgraph_fetcher.go
- nil/services/synccommittee/core/fetching/subgraph_fetcher_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/internal/metrics/sync_committee_metrics.go
- nil/services/synccommittee/internal/testaide/client_mock_block_setter.go
Changed block-related metrics published by `Sync Committee` to match the new batching model:
* Replaced `totalMainBlocksFetched` metric with `totalBatchesCreated` (counter);
* Fixed the way `batchSizeBlocks` metric is collected (moved it to `RecordBatchCreated` method);
* Replaced `txPerSingleProposal` metric published by `Proposer` with `batchSizeTxs` updated by `Aggregator`;
* Renaming: `total_l1_tx_sent` -> `total_l1_state_updates`; `block_total_time_ms` -> `batch_total_proof_time_ms`;
Implemented new background worker to track per-shard block fetching lag and publish corresponding metrics to `SigNoz`. By default, lag metrics are collected every 5 minutes
* Defined `LagTracker` - new `Sync Committee` worker, responsible for fetching lag tracking;
* Extended …
> Sync Committee: Batch Metrics + Lag Tracker

- explorer_frontend/src/features/tutorial-check/checks/tutorialFiveCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialFourCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialOneCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialThreeCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
- explorer_frontend/src/features/tutorial/assets/tutorialFive/tutorialFiveContracts.sol
- explorer_frontend/src/features/tutorial/assets/tutorialFive/tutorialFiveText.md
- explorer_frontend/src/features/tutorial/assets/tutorialFour/tutorialFourContracts.sol
- explorer_frontend/src/features/tutorial/assets/tutorialOne/tutorialOneContracts.sol
- explorer_frontend/src/features/tutorial/assets/tutorialThree/tutorialThreeContracts.sol
- explorer_frontend/src/features/tutorial/assets/tutorialThree/tutorialThreeText.md
- explorer_frontend/src/features/tutorial/assets/tutorialTwo/tutorialTwoContracts.sol
- explorer_frontend/src/features/tutorial/init.ts
- explorer_frontend/src/features/tutorial/model.ts
- explorer_frontend/src/features/tutorial/spec.ts
- nix/npmdeps.nix
- pnpm-lock.yaml
This diff adds several UX improvements to interactive tutorials.
- Added comments suggesting where exactly developers should add their code to tutorials.
- When a tutorial check fails and there is a fail receipt, the logs display the transaction hash for debugging.
- Completed solutions are cached and displayed when a developer accesses a completed tutorial.
- The text for most errors has been made clearer. 
Addresses #703 .
> [tutorial] added misc UX improvements

- nil/cmd/journald_forwarder/main.go
- nil/services/journald_forwarder/clickhouse.go
- nil/services/journald_forwarder/main.go
- nil/tests/journald_forwarder/journald_forwarder_test.go
In this PR, the entire batch of logs is stored in ClickHouse in a single query execution. This helps to avoid overloading ClickHouse with too many small queries.
- journald-forwarder services now send batch of events into clickhouse
- updated journald-forwarder tests
> [journald-forwarder] Implement store batch of events in one click request

- explorer_backend/config.ts
- explorer_backend/services/sqlite.ts
- nix/container.nix
This diff adds EXPLORER_DB (after renaming EXPLORER_CODE_SNIPPETS_DB_PATH) to the config so we can correctly use it. Outside the config which imports `import "dotenv/config";` we can not simply read env variables like `process.env.EXPLORER_DB`
This is needed to use bundled backend version on deployment host.
> [explorer] add EXPLORER_CODE_SNIPPETS_DB_PATH env var to config

- nil/internal/collate/validator.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/state.go
- nil/services/txnpool/txnpool.go
Zerolog doesn't deduplicate log entry tags. So it's enough to set shardId for root logger. Otherwise we will have shardId twice in JSON. This patch removes several FieldShardId fields in case if it's defined in the root logger.
> fix duplication of shardId in logs

- nil/contracts/solidity/tests/Stresser.sol
- nil/contracts/solidity/tests/Test.sol
- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/contracts/contract.go
- nil/internal/execution/state.go
- nil/internal/types/exec_errors.go
- nil/tests/regression/regression_test.go
- nix/tests-heavy.txt
- nix/tests-ibft.txt
Previously, big transactions just stuck in the pool/blocks, and the node tried to execute them again and again. Thus, a kind of infinite loop was observed.
This patch fixes it by adding constraint to the EVM that transaction cannot consume more than block gas limit. Also, the check for exceeding the gas limit has now been moved after adding a transaction, otherwise such a transaction would never appear in the block.
This solution has a drawback that the block can exceed its gas limit by two times in the worst case. In the future, we'll probably want to solve it more appropriately by reducing the possible excess of the block gas limit.
Relates to #79
> [execution] Fix big transactions processing

- nil/services/indexer/clickhouse/clickhouse.go
Otherwise, it fails in `indexer.go:112` line due to nil pointer dereference.
> [indexer] Fix clickhouse driver for empty blocks table

- flake.nix
- nil/cmd/proof_provider/main.go
- nil/cmd/prover/main.go
- nil/cmd/sync_committee/main.go
- nil/cmd/sync_committee_cli/main.go
Added `version` to the following binaries using `cobrax.VersionCmd`:
- `sync_committee`
- `sync_committee_cli`
- `proof_provider`
- `prover`
Renamed commands in `sync_committee_cli` for consistency: `get_tasks` -> `get-tasks`, `get_task_tree` -> `get-task-tree`
* Replaced repetitive version patching commands with a loop
* Added all binaries to the patching process
> Version command in SC binaries

- nil/contracts/solidity/tests/Test.sol
- nil/internal/vm/evm.go
- nil/tests/regression/regression_test.go
Empty salt produced address collision error that can't be fixed. This patch doesn't solve a problem completely (since it's possible to construct a salt manually that will cause collision with suggested by Create function). But it makes factories at least usable.
"Uniqueness" of salt consists of following components: [part of address] + [seqno] + [ext seqno].
> [vm] use different salts for contracts that's created from EVM

- nil/services/indexer/clickhouse/clickhouse.go
previously we were recreating db from scratch, but since currently cometa uses the same db this approach leads to problems
> make indexer removing only its tables instead of whole db

- rollup-bridge-contracts/contracts/NilRollup.sol
- rollup-bridge-contracts/contracts/interfaces/INilRollup.sol
- rollup-bridge-contracts/test/BaseTest.sol
- rollup-bridge-contracts/test/NilRollup.t.sol
Add state reset function to the rollup contract so an admin could revert to specified state root.
- Added `resetState` function. When called, it traverses a chain of `batchInfoRecords` (chained via `oldStateRoot`) until `newStateRoot` equals `targetStateRoot`, removing batch info and corresponding `stateRootIndex` entries. Any unrelated or dangling batch entries are left untouched.
- Remove `lastCommittedBatchIndex` since it is not used anyway, and to keep it consistent during state reset we had to introduce another `committedBatchHistory`.
> feat(rollup contract): add state reset function

- nil/cmd/nil/internal/contract/contract.go
- nil/cmd/nil/internal/contract/params.go
- nil/services/cliservice/contract.go
- nil/tests/cli/cli_test.go
We had a long debugging session yesterday with Oleg, trying to understand where the archive node's state has diverged from the validator. It would have been a bit easier to figure out which contract to blame if we could request the hash and storage root hash of that contract.
Fortunately, we already have the API for fetching debug information about smart contracts, which Sync Committee uses. I've just added an extension to our nil cli.
This will fetch and print contract information for the latest block:
```
nil contract [address]
```
And this will look at a particular block:
```
nil contract --block <block-id-or-tag> [address]
```
None
This is what the output looks like:
```
$ nil  contract 0x000414c4fffc36c28bea0ad38561b12ee628fdac
Hash: …
```
> Allow fetching contract info with "nil contract [address]"

- Makefile
- nil/internal/collate/metrics.go
- nil/internal/collate/validator.go
- nil/internal/execution/block_generator.go
- nil/internal/telemetry/telattr/metric.go
- nil/services/nilservice/service.go
Moved metrics from block generator to validator.
Validator is the correct place, because generator shouldn't produce side effects.
Separated block id from other metrics, so that it can be reported by syncers, not only by producers.
Part of https://github.com/NilFoundation/nil/issues/770
> [telemetry] Metrics for validators

- nil/services/rpc/rawapi/local_txnpool.go
- nil/services/rpc/transport/server.go
- nil/services/txnpool/txnpool.go
- nil/services/txnpool/txnpool_test.go
The problem was in the following.
Consider the case where two transactions with `seqno` 1 and 4 are added to the same account. Previously, after executing the transaction with `seqno` 1, the next `seqno` was set to 4. As a result, transactions with `seqno` 2 and 3 were rejected with a `Seqno too low` error. Now, the next `seqno` is set to 2, allowing transactions with `seqno` 2 and 3 to be processed as expected.
> [txpool] Fix seqno gap

- academy/token-split/task/deploy_and_test_tokensplitter.ts
- clijs/src/commands/smart-account/deploy.ts
- flake.nix
- niljs/package.json
- niljs/src/clients/CometaClient.ts
- niljs/src/clients/types/CometaTypes.ts
- niljs/src/encoding/toHex.ts
- niljs/src/utils/hex.ts
- niljs/test/integration/cometa.test.ts
- niljs/test/mocks/cometa-config.yml
- niljs/test/vitest.integration.config.ts
- nix/niljs.nix
This diff extends functionality of `CometaService` class of `niljs` so we can use new methods of cometa service, like `cometa_getSourceCode()` in other apps, for instance in block explorer.
In addition, this diff adds integration tests for cometa service to niljs.
In addition, it slighly changes the interfaces of `registerContract()` and `compileContract()`, because for js-users it is going to be much more convenient to provide an object to this method. Previously we accepted only json-like string.
> Add cometa niljs integration tests

- explorer_frontend/.env
- explorer_frontend/src/features/shared/components/Layout/Logo.tsx
- explorer_frontend/src/features/shared/components/Layout/Navbar.tsx
- explorer_frontend/src/features/shared/components/Layout/index.tsx
- explorer_frontend/src/features/shared/components/Layout/styles.ts
- explorer_frontend/src/features/shared/index.ts
- explorer_frontend/src/pages/playground/PlaygroundPage.tsx
- explorer_frontend/src/pages/tutorials/TutorialPage.tsx
- flake.nix
- nix/nilexplorer.nix
This diff adds `Playground v123` text to playground logo if version is specified.
The version is injected as `env` during the build because it is not a subject to be changed after the app is built.
> [playground] add Playground version to playground logo

- nil/cmd/relayer/main.go
Adding forgotten config flag for setting private key file for the relayer. It is needed for customizing deployment of the service to different environments
> relayer: add forgotten pk config flag

- nil/internal/collate/block_listener.go
- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/tests/async_await/async_await_test.go
- nil/tests/common.go
- nil/tests/sharded_suite.go
Some improvements made after testing archive nodes with relays.
- Archive nodes serve blocks over libp2p: call SetBlockRequestHandler in syncer.
- Update to syncer init: no bootstrap peers is fine; more explicit handling of the absence of peers with whom to check the version.
Part of https://github.com/NilFoundation/nil/issues/489
> [archive] Misc improvements concerning relays

- .golangci.yml
- nil/client/rpc/client.go
- nil/cmd/nil/common/args.go
- nil/cmd/nil/internal/cometa/command.go
- nil/cmd/nil/internal/contract/call-readonly.go
- nil/cmd/nil/internal/debug/debug.go
- nil/cmd/nil/internal/smartaccount/call-readonly.go
- nil/cmd/nil/internal/smartaccount/deploy.go
- nil/services/admin/server_test.go
- nil/services/cliservice/faucet.go
- nil/services/cometa/client.go
- nil/services/faucet/client.go
- nil/services/nil_load_generator/client.go
- nil/services/rpc/internal/http/http_test.go
- nil/services/rpc/internal/http/testaide.go
- nil/services/stresser/core/helper.go
- nil/tests/cometa/cometa_test.go
- nil/tests/faucet/faucet_test.go
- nil/tests/faucet_service/faucet_service_test.go
- nil/tests/nil_load_generator_service/nil_load_generator_test.go
There was some code duplication in different rpc clients: for cometa, faucet, loadgen. This patch reduces it. Here we will use a common method that performs HTTP JSONRPC request.
> [rpc] move common code into a function

- explorer_frontend/src/features/contracts/components/Management/MethodInput.tsx
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/contracts/utils.tsx
- explorer_frontend/src/features/logs/init.tsx
This PR adds support to work with arrays in the playground and also parses tuple results which was not possible before. 
- Fix `MethodInput.tsx` for accepting an input. Previously, it would fill the input tab with `[object Object]` when you enter anything in the input placeholder
- Add support to input array type elements
- Fix parsing of tuples upon a view function call which returns a tuuple. Previously this would have resulted in `[object Object]` as the result of the function call
Fixes https://github.com/NilFoundation/nil/issues/496
None
None
This PR aims at solving the issues related to inputs that have been remained till now. To test all the inputs, there is a test contract. Copy this contract into the playground(local version) and compile and deploy and then call all the `store` …
> [playground] : added support for inputting arrays and tuple result parsing

- nil/cmd/relay/main.go
`relay gen-config` overwrites existing config. (This is the way `nild gen-configs` acts.)
Required to deploy relay in the cluster.
> [relay] Overwrite existing config

- flake.nix
Passing nil as a default input causes rebuild of niljs on every cluster code change.
> [niljs] remove nil from default nix package inputs

- Makefile
- nil/cmd/nil-relay/main.go
`nil-relay` is more clear and safe than `relay`.
> [relay] Rename cmd to nil-relay

- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/internal/api/task_request_handler.go
- nil/services/synccommittee/internal/executor/task_executor_test.go
- nil/services/synccommittee/internal/rpc/task_request_rpc_client.go
- nil/services/synccommittee/internal/scheduler/task_cancel_checker.go
- nil/services/synccommittee/internal/scheduler/task_cancel_checker_test.go
- nil/services/synccommittee/internal/scheduler/task_scheduler.go
- nil/services/synccommittee/internal/storage/task_storage.go
- nil/services/synccommittee/internal/storage/task_storage_test.go
- nil/services/synccommittee/internal/types/errors.go
- nil/services/synccommittee/internal/types/task_result.go
- nil/services/synccommittee/proofprovider/service.go
- nil/services/synccommittee/public/task_view.go
If parent task on `sync committee` level was cancelled, during reset the child tasks should not be executed.
This change affects only `proof-provider` .
- Added `CanlcelDeadTasks` public method to task storage
- Added `TaskCancelChecker` worker and run in under `proof-provider` process
- Extended `TaskRequestHandler` api by `CheckIfTaskExists` (implemented in `taskScheduler` and `taskRequestRpcClient`)
- Added tests for `TaskCancelChecker` and `TaskStorage::CanlcelDeadTasks`
https://www.notion.so/nilfoundation/Child-tasks-cancellation-162c61485260803882b3e50b89d2f5c4
> sync-committee: child tasks cancellation

- nil/cmd/relayer/main.go
This PR fixes invalid setup of the log level CLI flag (it was overwritten by subcommand flags instead of preserving)
> relayer: fix log-level flag

- docs/docusaurus.config.js
- docs/nil/migration-guides/april-1604-2025-release.mdx
- docs/sidebar-nil.js
This diff adds a new migration guide to docs to cover the 16/04/2025 release.
- Added a new migration guide for the 16/04/2025 release
- Added the wallet extension to the dev tools dropdown
Please mark each item with an `x` inside the brackets (e.g., [x]) once completed._
> [docs] added a migration guide for the 16/04 release

- clijs/src/commands/smart-account/call-readonly.ts
- clijs/src/commands/smart-account/deploy.ts
- clijs/src/commands/smart-account/estimate-fee.ts
- clijs/src/commands/smart-account/new.ts
- clijs/src/commands/smart-account/send-tokens.ts
- clijs/src/commands/smart-account/send-transaction.ts
- clijs/src/commands/smart-account/top-up.ts
If I run `clijs` without bundling through `dev.js` or `run.js`, I get a ton of errors:
<details>
<summary>Log</summary>
```
$ ./bin/dev.js 
(node:3343624) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:3343624) Warning: Error
module: @oclif/core@4.2.10
task: findCommand (smart-account:call-readonly)
plugin: @nilfoundation/clijs
root: /home/un1or/projects/nil/nil-public/clijs
message: Cannot find module '/home/un1or/projects/nil/nil-public/clijs/dist/src/common/utils' imported from /home/un1or/projects/nil/nil-public/clijs/dist/src/commands/smart-account/call-readonly.js
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: Error
at …
```
> [GH-#] dev.js/run.js fix

- explorer_frontend/package.json
- explorer_frontend/src/features/account/components/AccountInfo.test.tsx
- explorer_frontend/src/features/account/components/AccountInfo.tsx
- explorer_frontend/tests/unit/TestsLayout.tsx
- explorer_frontend/tests/unit/renderWithLayout.ts
- explorer_frontend/tests/unit/setupUnitTests.ts
- explorer_frontend/tests/vitest.config.ts
- explorer_frontend/tsconfig.json
- explorer_frontend/typings.d.ts
- explorer_frontend/vite.config.ts
- nix/nilexplorer.nix
- nix/npmdeps.nix
- pnpm-lock.yaml
This diff enables uint testing in explorer_frontend.
For the tests to run special environment is required, creating `baseui` styles provider.
Also, this diff contains an example of unit test for `AccountInfo` component.
Let's follow the AAA scheme for writing tests for clarity and readability.
`Arrange`
new line...
`Action`
new line...
`Assert`
> [explorer] add unit tests setup and AccountInfo test for explorer

- academy/lending-protocol/contracts/LendingPool.sol
- academy/lending-protocol/deep_dive_into_the_protocol.md
- academy/token-split/contracts/tokenSplitter.sol
- docs/nil/guides/app-migration.mdx
- docs/nil/smart-contracts/pre-compiles.mdx
- docs/tests/AsyncToken.sol
- docs/tests/SwapMatch.sol
- docs/tests/SwapMatchPure.sol
- nil/contracts/solidity/tests/RequestResponseTest.sol
- nil/contracts/solidity/tests/TokensTest.sol
- nil/internal/vm/precompiled.go
- nil/services/rpc/rawapi/internal/local_account.go
- nil/tests/multitoken/multitoken_test.go
- niljs/src/contract-factory/contracts/ContractFactoryTest.sol
- smart-contracts/contracts/Nil.sol
- smart-contracts/contracts/TokenManager.sol
- uniswap/contracts/UniswapV2Router01.sol
> [PoC] Pure tokens sync transfer

- nil/contracts/solidity/tests/TokensTest.sol
- nil/internal/execution/state.go
- nil/internal/execution/transactions.go
- nil/internal/types/exec_errors.go
- nil/internal/vm/interface.go
- nil/internal/vm/precompiled.go
- nil/services/rpc/rawapi/internal/local_call.go
- nil/tests/request_response/request_response_test.go
- smart-contracts/contracts/Nil.sol
Here we merge sendRequest precompile code into asyncCall precompile.
At first it allows to eliminate code duplication and then it's the first step before implementation Awaiter contract that will include some request/response machinery for response processing.
> merge sendRequest precompile into asyncCall

- nil/services/synccommittee/core/batches/blob/builder.go
- nil/services/synccommittee/core/fetching/aggregator.go
- nil/services/synccommittee/core/fetching/aggregator_test.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/proposer_test.go
- nil/services/synccommittee/core/reset/resetter.go
- nil/services/synccommittee/core/reset/state_reset_launcher.go
- nil/services/synccommittee/core/rollupcontract/commit_batch.go
- nil/services/synccommittee/core/rollupcontract/errors.go
- nil/services/synccommittee/core/rollupcontract/update_state.go
- nil/services/synccommittee/core/rollupcontract/wrapper.go
- nil/services/synccommittee/core/rollupcontract/wrapper_test.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/core/service_test.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/testaide/client_mock_block_setter.go
Sync committee. Handle CommitBatch errors, add simulation before tx submission.
- Add simulation before submitting each transaction to L1 to catch errors early.
- If simulation fails, parse the RPC error; depending on its type, the `CommitBatch` method either panics or triggers a state resync from L1 (e.g., when multiple SC instances are running and local state is stale).
- Move L1 finalized state fetcher to a separate class for better modularity.
- Pass the fetcher into both aggregator and proposer components so they can detect outdated local state and initiate L1 synchronization.
> feat(sc): handle CommitBatch errors, add simulation before tx submission

- nil/services/relayer/Makefile.inc
Follow up fix to the https://github.com/NilFoundation/nil/pull/839
- embed_abi targets depend on compile_abi (order of execution is not guaranteed otherwise)
> fix relayer Makefile

- nil/client/rpc/client.go
- nil/internal/mpt/proof.go
- nil/internal/mpt/proof_test.go
- nil/internal/types/storage.go
- nil/services/rpc/jsonrpc/eth_accounts.go
- nil/services/rpc/jsonrpc/eth_accounts_test.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/synccommittee/prover/tracer/internal/mpttracer/serialization.go
- nil/services/synccommittee/prover/tracer/internal/mpttracer/types.go
Implement _eth_getProof_ RPC method for zeth proof collection. **NOTE: SSZ serialization is used instead of RLP.**
- Added `mpt.SimpleProof` to support Ethereum's proof structure, which differs from our existing `mpt.Proof`:
- Contains only nodes without key and operation type
- Serialized as [][]byte where each []byte is a serialized node (vs. single SSZ structure)
- Leveraged existing `GetContract` method in raw API which already returns account proof and full account storage, rather than adding a new raw API method. Implementation parses this response on the JSON-RPC side and formats it to match Ethereum's expected proof structure.
> feat(RPC): add eth_getProof method

- nil/contracts/generate.go
- nil/internal/contracts/contract.go
- nil/internal/contracts/contract_test.go
- nil/internal/execution/state_trace.go
- nil/services/cometa/contract.go
Now all embedded contracts (those located in `ni/contracts/solidity` folder) have `func_id => signature` map.
It allows decoding their calldata from anywhere.
> [execution] Store function signatures for embedded contracts

- nix/npmdeps.nix
Update pnpm deps hash for fix local build
Update pnpm hash
`sha256-C92pv9JoeUGn+WcEV1hBisuIYGhx+mpZsylYA1Q89F8=` => `sha256-IH6aBVjiCspk763jdIbf/1scXgU2pedi3bgLvc0NlvU=`
> update npm hash

- nil/services/synccommittee/Makefile.inc
- nil/services/synccommittee/core/batches/constraints/checker.go
- nil/services/synccommittee/core/batches/constraints/constraint_size.go
- nil/services/synccommittee/core/batches/constraints/constraint_timeout.go
- nil/services/synccommittee/core/batches/constraints/constraints.go
- nil/services/synccommittee/core/batches/constraints/result.go
- nil/services/synccommittee/core/block_batch_test.go
- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/core/fetching/aggregator.go
- nil/services/synccommittee/core/fetching/aggregator_test.go
- nil/services/synccommittee/core/fetching/block_range_fetcher.go
- nil/services/synccommittee/core/fetching/lag_tracker_test.go
- nil/services/synccommittee/core/proposer_test.go
- nil/services/synccommittee/core/reset/state_reset_launcher.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/core/task_state_change_handler.go
- nil/services/synccommittee/core/task_state_change_handler_test.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_entries.go
- nil/services/synccommittee/internal/storage/block_storage_op_batch.go
- nil/services/synccommittee/internal/storage/block_storage_op_block.go
- nil/services/synccommittee/internal/storage/block_storage_op_blocks_latest_fetched.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
- nil/services/synccommittee/internal/testaide/blocks.go
- nil/services/synccommittee/internal/types/block_batch.go
- nil/services/synccommittee/internal/types/blocks.go
- nil/services/synccommittee/internal/types/blocks_test.go
- nil/services/synccommittee/internal/types/prover_tasks.go
Refactor `aggregator` logic for batch processing and validation.
Now, instead of creating a separate batch for each individual subgraph, a batch is constructed from an arbitrary number of blocks based on constraints.
* Integrated `BatchConstraintChecker` and `fetcher` into `Aggregator`;
* Rewrote the `aggregator.processBlockRange` method;
* Adjusted the `BlockBatch` structure to support explicit sealing;
* Modified all existing `Aggregator` tests;
Introduced a mechanism to lazily fetch block range from a specific shard
* Introduced `fetcher` type (will be used by `aggregator`);
* Implemented `BlocksRange.SplitToChunks()` method;
* Introduced `checker` type to manage batch constraints implementing `batchConstraintRunner` interface;
* Implemented `sizeConstraint` and `timeoutConstraint`; …
> Sync Committee: Batch Constraints

- clijs/bin/dev.js
- clijs/bin/run.js
- clijs/src/base.ts
- clijs/src/commands/block.ts
- clijs/src/commands/receipt.ts
- clijs/src/common/config.test.ts
- clijs/src/sea.ts
- clijs/test/commands/receipt.test.ts
- clijs/test/setup.ts
- niljs/src/clients/BaseClient.ts
- niljs/src/utils/faucet.ts
add receipt command to clijs. also during this I noticed that the CLI hangs for ~5-10 seconds after finishing the command logic
main reason seems to be in many promises hanging inside the node event loop. those are created during package imports or some open-rpc connections and closed only by timeout. so this PR also adds logic to exit from the process on success
> [clijs] add receipt command

- nil/client/client.go
- nil/internal/collate/proposer.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/testaide.go
- nil/internal/execution/zerostate.go
- nil/internal/execution/zerostate_test.go
- nil/internal/types/Makefile.inc
- nil/internal/types/account.go
- nil/internal/types/block.go
- nil/internal/types/collator.go
- nil/internal/types/exec_errors.go
- nil/internal/types/log.go
- nil/internal/types/receipt.go
- nil/internal/types/signature.go
- nil/internal/types/transaction.go
- nil/internal/types/version_info.go
- nil/services/faucet/jsonrpc.go
- nil/services/rpc/jsonrpc/txpool_api_test.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/rpc/types/types.go
- nil/services/synccommittee/internal/testaide/blocks.go
- nil/services/synccommittee/prover/tracer/tracer_mock_client_test.go
- nil/services/txnpool/txnpool_test.go
- nil/tests/basic/basic_test.go
- nil/tests/modifiers/rpc_modifiers_test.go
- nil/tests/regression/regression_test.go
- nix/nil.nix
- uniswap/contracts/UniswapV2Router01.sol
This patch set contains two improvements:
* Reducing code duplication via reusing FeePack structure
* Replacing "go:generate" directives to Makefile usage (just to support only one build system and also it will be useful in future when we will change SSZ to RLP encoding).
> [types] build/usage improvements

- clijs/src/commands/block.ts
- clijs/src/commands/receipt.ts
- clijs/test/commands/receipt.test.ts
- clijs/vitest.config.ts
Enable `disableConsoleIntercept` according to the [documentation](https://www.npmjs.com/package/@oclif/test) and check the output of the command.
Also, the receipt itself is now output in JSON format instead of JavaScript object literal.
> [GH-#] Check stdout in tests

- clijs/test/commands/abi/encode-decode.test.ts
- clijs/test/commands/block.test.ts
- clijs/test/commands/receipt.test.ts
- clijs/test/commands/smart-account/balance.test.ts
- clijs/test/commands/smart-account/deploy.test.ts
- clijs/test/commands/smart-account/estimate.test.ts
- clijs/test/commands/smart-account/new.test.ts
- clijs/test/commands/smart-account/send-token.test.ts
- clijs/test/globalSetup.ts
- clijs/test/testEnv.ts
- clijs/vitest.config.ts
- nix/clijs.nix
this PR makes clijs tests self-sufficient, now you need to provide `nild` binary to correctly run tests
> start nild binary inside clijs tests

- nil/internal/vm/memory_table.go
Use the built-in max/min from the standard library in Go 1.21 to simplify the code.
> refactor: use the built-in max/min to simplify the code

- README.md
> docs: correct “go run spec_generator” command syntax

- nil/internal/config/generate.go
- nil/internal/types/transaction.go
- nil/services/rpc/filters/filters_test.go
It's unused after d391624f4f64524aed14ecd139e2fa4bbbc21d8c.
> [types] drop unused EvmState struct

- nil/common/concurrent/suspendable.go
- nil/common/concurrent/suspendable_test.go
- nil/common/logging/fields.go
- nil/services/synccommittee/core/fetching/aggregator.go
- nil/services/synccommittee/core/fetching/lag_tracker.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/reset/state_reset_launcher.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/internal/executor/task_executor.go
- nil/services/synccommittee/internal/executor/task_executor_test.go
- nil/services/synccommittee/internal/metrics/basic_metrics.go
- nil/services/synccommittee/internal/scheduler/task_cancel_checker.go
- nil/services/synccommittee/internal/scheduler/task_cancel_checker_test.go
- nil/services/synccommittee/internal/scheduler/task_result_sender.go
- nil/services/synccommittee/internal/scheduler/task_result_sender_test.go
- nil/services/synccommittee/internal/scheduler/task_scheduler.go
- nil/services/synccommittee/internal/srv/heartbeat_sender.go
- nil/services/synccommittee/internal/srv/log.go
- nil/services/synccommittee/internal/srv/noop_worker_metrics.go
- nil/services/synccommittee/internal/srv/service.go
- nil/services/synccommittee/internal/srv/service_test.go
- nil/services/synccommittee/internal/srv/worker.go
- nil/services/synccommittee/internal/srv/worker_iteration.go
- nil/services/synccommittee/internal/srv/worker_loop.go
- nil/services/synccommittee/proofprovider/service.go
- nil/services/synccommittee/prover/service.go
Refactor `Worker`'s initialization and logging, introduce `HeartbeatSender`
* Implemented a new `HeartbeatSender` worker updating the new heartbeat counter metric with a static interval;
* Integrated logger and basic metrics into `srv.WorkerLoop` to mandatorily log unhandled errors and publish error-related metrics;
Other changes:
* Increased the default task polling interval from `1 sec` to `10 sec` to reduce the number of requests between nodes;
* Removed unused interfaces, renamed a couple of types;
> Sync Committee: Heartbeat + Worker Metrics

- nil/services/nilservice/service.go
Nild: Fix Indexer RPC. Enable only indexer-rpc without running indexer task
- [v] I have read and followed the [Contributing Guide](https://github.com/NilFoundation/nil/blob/main/CONTRIBUTION-GUIDE.md)
- [v] I have tested the changes locally
- [v] I have added relevant tests (if applicable)
- [v] I have updated documentation/comments (if applicable)
> nilservice: indexer rpc fix

- nil/services/synccommittee/core/block_tasks_integration_test.go
- nil/services/synccommittee/core/fetching/aggregator_test.go
- nil/services/synccommittee/core/task_state_change_handler_test.go
- nil/services/synccommittee/internal/api/task_request_handler.go
- nil/services/synccommittee/internal/executor/id_source.go
- nil/services/synccommittee/internal/executor/id_source_test.go
- nil/services/synccommittee/internal/executor/task_executor.go
- nil/services/synccommittee/internal/executor/task_executor_test.go
- nil/services/synccommittee/internal/rpc/task_debug_rpc_test.go
- nil/services/synccommittee/internal/rpc/task_request_handler_rpc_suite_test.go
- nil/services/synccommittee/internal/rpc/task_request_handler_rpc_test.go
- nil/services/synccommittee/internal/rpc/task_request_rpc_client.go
- nil/services/synccommittee/internal/scheduler/task_cancel_checker.go
- nil/services/synccommittee/internal/scheduler/task_cancel_checker_test.go
- nil/services/synccommittee/internal/scheduler/task_result_sender_test.go
- nil/services/synccommittee/internal/scheduler/task_scheduler.go
- nil/services/synccommittee/internal/storage/executor_id_storage.go
- nil/services/synccommittee/internal/storage/task_result_storage_test.go
- nil/services/synccommittee/internal/storage/task_storage_test.go
- nil/services/synccommittee/internal/testaide/prover_tasks.go
- nil/services/synccommittee/internal/types/prover_tasks.go
- nil/services/synccommittee/proofprovider/service.go
- nil/services/synccommittee/proofprovider/task_handler_test.go
- nil/services/synccommittee/proofprovider/task_state_change_handler.go
- nil/services/synccommittee/prover/service.go
Refactor `TaskExecutor` and related components to use `executor.IdSource` for generating `TaskExecutorId`
Previously, both `Prover` and `ProofProvider` used random "nonce" IDs that were regenerated on each service startup. While it's fine for `Prover` to use a volatile identifier, `ProofProvider` requires a persistent ID to support top-level task result submission after a restart
Introduced `IdSource` implementations:
* `InMemoryIdSource` – used by `Prover`
* `PersistentIdSource` – backed by a database and used by `ProofProvider`
> Proof Provider: Persistent TaskExecutorId

- nil/services/synccommittee/core/batches/constraints/checker.go
- nil/services/synccommittee/core/batches/constraints/result.go
- nil/services/synccommittee/core/fetching/aggregator.go
- nil/services/synccommittee/core/fetching/aggregator_test.go
- nil/services/synccommittee/core/task_state_change_handler.go
- nil/services/synccommittee/internal/metrics/task_storage_metrics.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_op_batch_count.go
- nil/services/synccommittee/internal/storage/block_storage_test.go
This PR addresses the following error encountered on `nil-dev` after a full state reset was triggered:
```
error preparing batch: error loading latest batch from the storage: batch with the specified id is not found, id=23d4376b-f92e-488a-abb6-8a3dc8cf6c20
```
Changes:
* Fixed `BlockStorage.ResetAllBatches(...)` by setting `latestBatchId` to `nil`
* Added `BlockStorage.HasFreeSpace(...)` method to avoid unnecessary batch creation in `Aggregator`
> Sync Committee: Block Storage Fix

- clijs/src/commands/config/get.ts
- clijs/src/commands/config/init.ts
- clijs/src/commands/config/set.ts
- clijs/src/commands/config/show.ts
- clijs/src/common/config.ts
- clijs/src/sea.ts
- clijs/test/commands/config.test.ts
- clijs/tsconfig.json
Implement config commands
- config init
- config get
- config set
- config show
Fixed #454
- [v] I have read and followed the [Contributing Guide](https://github.com/NilFoundation/nil/blob/main/CONTRIBUTION-GUIDE.md)
- [v] I have tested the changes locally
- [v] I have added relevant tests (if applicable)
- [v] I have updated documentation/comments (if applicable)
> clijs: implement config commands

- nil/services/relayer/internal/debug/debug.go
- nil/services/relayer/service.go
For the testing purposes we need a convenient way to fetch relayer L2 smart account addr. Added it to the debug API
> relayer: expose smart account addr via debug api

- nil/internal/profiling/profiling.go
I've found it unfortunate that cluster node pprof is not available from the external network (and it's hard to get profiles from the cluster machines).
> [pprof] Serve on pprof port for external network too

- nil/cmd/proof_provider/main.go
- nil/cmd/prover/main.go
Added `--metrics` flag to the `prover` binary configuration
Corresponding PR in `infra`: https://github.com/NilFoundation/infra/pull/721
> Prover: Metrics Flag in Config

- nil/services/rpc/jsonrpc/eth_accounts.go
- nil/services/rpc/jsonrpc/eth_accounts_test.go
- nil/services/rpc/jsonrpc/types.go
Add `address` field to `eth_getProof` response
- Add `address` field to `eth_getProof` response
- Adjust tests
- Adjust docstrings for `EthProof` structure
Fixes to https://github.com/NilFoundation/nil/pull/851
> fix(RPC): add `address` field to `eth_getProof` response

- nil/services/relayer/internal/debug/debug.go
- rollup-bridge-contracts/test_integration.sh
Added small fix to relayer debug api namespace and example of usage into the rollup bridge contracts integration test
> fix relayer debug API

- flake.nix
- nil/services/rpc/jsonrpc/debug_api.go
- nix/nil.nix
- rollup-bridge-contracts/test_integration.sh
It's too long to build all binaries and then upload their cache to S3. After this patch we will build only nild and nil packages for niljs, nildocs, etc tests.
> [nix] build only nil/nild binaries for dependencies tests

- niljs/src/transport/HttpTransport.ts
This diff fixes the problem with calling fetch on `globalThis` object in niljs.
> fix: fix calling fetch in niljs http transport

- create-nil-hardhat-project/package.json
- hardhat-plugin/package.json
- niljs/package.json
- pnpm-lock.yaml
- rollup-bridge-contracts/package.json
- smart-contracts/package.json
Bumping versions for release:
niljs
smart-contracts
create-nil-hardhat-project
hardhat-plugin
rollup-bridge-contracts
> [release] Bump js lib versions

- flake.nix
- nil/services/rpc/internal/http/connection.go
Release changes:
- Switching from poseidon to Keccak256 as hash function
- For more compatibility with Etherium all data now serialised using RLP mechanism instead of SSZ
> Release 2025.05.15 (0.2.0)

- docs/nil/nil-101.mdx
The tutorial’s install command pointed to  `https://github.com/NilFoundation/nil/raw/master/install.sh`,  which now returns **404**.  
This PR updates the link to the maintained script at  
`https://github.com/NilFoundation/nil/blob/main/scripts/install_cli.sh`,  
restoring a working one-line installer for the =nil; CLI and preventing installation errors for new users.
> docs(nil-101): replace broken CLI installer URL

- nil/cmd/sync_committee_cli/internal/commands/executor.go
- nil/cmd/sync_committee_cli/main.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/debug/client.go
- nil/services/synccommittee/internal/debug/block_debugger.go
- nil/services/synccommittee/internal/debug/task_debugger.go
- nil/services/synccommittee/internal/rpc/block_debug_rpc_client.go
- nil/services/synccommittee/internal/rpc/block_debug_rpc_test.go
- nil/services/synccommittee/internal/rpc/client.go
- nil/services/synccommittee/internal/rpc/server_suite_test.go
- nil/services/synccommittee/internal/rpc/server_with_tasks.go
- nil/services/synccommittee/internal/rpc/task_debug_rpc_client.go
- nil/services/synccommittee/internal/rpc/task_debug_rpc_test.go
- nil/services/synccommittee/internal/rpc/task_request_handler_rpc_test.go
- nil/services/synccommittee/internal/rpc/task_request_rpc_client.go
- nil/services/synccommittee/internal/storage/block_storage.go
- nil/services/synccommittee/internal/storage/block_storage_op_batch.go
- nil/services/synccommittee/proofprovider/service.go
- nil/services/synccommittee/public/batch_view.go
- nil/services/synccommittee/public/block_debug_api.go
- nil/services/synccommittee/public/list_request_common.go
- nil/services/synccommittee/public/task_debug_api.go
Now SC, in addition to task-related methods, exposes a block debugging API, which provides the following data:
* State root (both local and L1)
* Latest fetched blocks across all shards
* Detailed information about a specific block batch (full list of block hashes, when it was created, etc.)
* List of `K` most recently created batches
* Statistics about currently stored batches
The client part will be added to `sync_committee_cli` in a follow-up PR
> Sync Committee: Block Debugger API

- explorer_frontend/src/features/healthcheck/components/NetworkErrorNotification.tsx
This diff fixes `NetworkErrorNotification` component imports section. The `useMobile` import was deleted accidentally.
> fix: fix NetworkErrorNotification imports

- nil/common/concurrent/utils.go
- nil/internal/collate/bootstrap.go
- nil/internal/collate/syncer.go
- nil/internal/collate/version.go
- nil/services/indexer/badger/badger.go
- nil/services/indexer/clickhouse/clickhouse.go
- nil/services/indexer/driver/driver.go
- nil/services/indexer/fetch_block.go
- nil/services/indexer/indexer.go
- nil/tests/archive_node/complex_test.go
Syncing nodes stop if the chain or protocol version changed.
Indexer stops if the chain version changed.
Changes:
- Moved existing version-related stuff to a separate file and refactored a bit for my needs.
- Added a version check loop to the syncers (called on the main shard syncer only).
- Added a version check loop to the indexer.
- Refactored indexer a bit.
- Implemented version check and db reset in badger indexer.
Fixes https://github.com/NilFoundation/nil/issues/769 and https://github.com/NilFoundation/nil/issues/659
Tested locally:
1. Start cluster -> Start archive node -> Stop cluster; drop validator keys and db (keep network keys); start the cluster anew -> Archive node stops after discovering the change in the version.
2. Same for indexer instead of archive.
> [version] Restart services on chain or protocol change

- nil/services/relayer/internal/l2/contract_wrapper.go
- rollup-bridge-contracts/test_integration.sh
relayMessage is not a payable function and should be executed with zero value. Fixed the bug and enabled full integration test for the rollup bridge contracts
> enable full pipeline in bridge integration test

- nil/services/synccommittee/core/bridgecontract/bridge_state_getter.go
- nil/services/synccommittee/core/feeupdater/updater_test.go
- nil/services/synccommittee/core/proposer.go
- rollup-bridge-contracts/task/validate-l2-eth-bridging.ts
By mistake used invalid type for referencing a block while getting bridge state from the L2 contract
> bridge state getter: fix block ref type

- .github/workflows/main.yml
- clijs/test/globalSetup.ts
- clijs/vitest.config.ts
The `nix_check_macos` matrix job has been added.
First we try to authorize our workflow via OIDC for write access in AWS to the Nix cache. This is possible for main and PR's according to the role settings. For runs via `workflow_dispatch` and forks, the access will be read-only. The cache bucket is made public read-only for this purpose.
Restored `clijs` builds for macOS `aarch64` & `x86_64`. Also added `nil` builds for the same platforms, but disabled for `x86_64` for now due to test issues. I plan to deal with this later and leave only Nix builds for macOS.
> [GH-240] Nix cache for macOS CI

- README.md
Keeps GetShardIdList() only under “Shards”, eliminating redundancy and clarifying RPC grouping for integrators and tooling.
> docs: remove duplicate GetShardIdList() from Filters section

- nil/cmd/sync_committee_cli/internal/commands/batch_fields.go
- nil/cmd/sync_committee_cli/internal/commands/get_batch.go
- nil/cmd/sync_committee_cli/internal/commands/get_batch_stats.go
- nil/cmd/sync_committee_cli/internal/commands/get_batches.go
- nil/cmd/sync_committee_cli/internal/commands/get_latest_fetched.go
- nil/cmd/sync_committee_cli/internal/commands/get_state_root_data.go
- nil/cmd/sync_committee_cli/internal/commands/get_task_tree.go
- nil/cmd/sync_committee_cli/internal/commands/get_tasks.go
- nil/cmd/sync_committee_cli/internal/commands/params_with_endpoint.go
- nil/cmd/sync_committee_cli/internal/commands/task_fields.go
- nil/cmd/sync_committee_cli/internal/commands/task_fields_flag.go
- nil/cmd/sync_committee_cli/internal/output/builder.go
- nil/cmd/sync_committee_cli/internal/output/table.go
- nil/cmd/sync_committee_cli/main.go
- nil/services/synccommittee/public/batch_view.go
- nil/services/synccommittee/public/block_debug_api.go
- nil/services/synccommittee/public/list_request_common.go
- nil/services/synccommittee/public/task_debug_api.go
Retrieves the current state root data, including both the L1 and local state roots.
```shell
❯ ./sync_committee_cli get-state-root-data
| Field            | Value                                                              |
|------------------|--------------------------------------------------------------------|
| L1 State Root    | 0x0000000000000000000000000000000000000000000000000000000000000000 |
| Local State Root | nil                                                                |
```
Returns detailed information about a specific block batch identified by a `BatchId`.
```shell
❯ ./sync_committee_cli get-batch --batch-id 5f4d76de-f4a8-4ce2-9ee4-cf096bae71ec
{
"id": "5f4d76de-f4a8-4ce2-9ee4-cf096bae71ec",
"parentId": "9ab2c2af-5366-4cd6-bad8-200651309dde",
"isSealed": false, …
```
> Sync Committee CLI: Block and Batch Diagnostics

- explorer_frontend/src/pages/address/AddressPage.tsx
- explorer_frontend/src/pages/block/BlockPage.tsx
This diff fixes tabs navigation on block and account pages by making this navigation "invisible" to browser.
fixes #919
> [explorer] fix block and account tabs navigation

- explorer_frontend/src/features/shared/components/Layout/Logo.tsx
- explorer_frontend/src/features/shared/components/Layout/Navbar.tsx
- explorer_frontend/src/pages/playground/PlaygroundPage.tsx
- explorer_frontend/src/pages/tutorials/TutorialPage.tsx
This diff removes logo subtitle from explorer page and makes components architecture easier to maintain.
> [explorer] fix playground logo title

- niljs/README.md
- niljs/src/contract-factory/ContractFactory.ts
Hey team! Fixed errors in niljs/README.md and niljs/src/contract-factory/ContractFactory.ts
`unsuccesful` - `unsuccessful`
`inferrable` - `inferable`
> fix spelling issues

- nil/services/synccommittee/core/bridgecontract/bridge_state_getter.go
- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/core/proposer_test.go
- nil/services/synccommittee/core/service.go
* Use the corresponding main shard hash to invoke the L2 bridge messenger contract instead of the block from the shard with id `BridgeStateKeeperShardId`.
* Add a contract existence check to `BridgeStateGetter` to return an empty state if the contract does not yet exist at the specified block.
> Sync Committee: Fix Bridge State Getter

- explorer_frontend/src/features/search/components/Search.tsx
- explorer_frontend/src/features/shared/components/Heading/index.tsx
- explorer_frontend/src/pages/explorer/styles.ts
This diff restores the search bar on the main part, but in an appropriate place like on the design template.
> [explorer] add search bar to the main page

- nil/internal/db/accessors.go
- nil/services/rpc/rawapi/pb/conversion.go
- nil/tests/rpc_node/call_test.go
Added functions that wrap transaction's Get method and add shard id, table name and key to the ErrKeyNotFound message.
Only message is used and not a new error struct type, because it is intended only for debug purposes (e.g., I don't expect it to be passed via API to puzzle the users).
> [db] Getters with extended error message (shard, table, key)

- nil/Makefile.inc
- nil/internal/types/Makefile.inc
* fixed double include that produced following warning:
```
nil/internal/types/Makefile.inc:27: warning: overriding recipe for target 'nil/internal/types/error_string.go'
nil/internal/types/Makefile.inc:27: warning: ignoring old recipe for target 'nil/internal/types/error_string.go'
nil/internal/types/Makefile.inc:35: warning: overriding recipe for target 'nil/internal/types/signature_rlp_encoding.go'
nil/internal/types/Makefile.inc:35: warning: ignoring old recipe for target 'nil/internal/types/signature_rlp_encoding.go'
nil/internal/types/Makefile.inc:38: warning: overriding recipe for target 'nil/internal/types/log_rlp_encoding.go'
nil/internal/types/Makefile.inc:38: warning: ignoring old recipe for target 'nil/internal/types/log_rlp_encoding.go'
nil/internal/types/Makefile.inc:41: …
```
> [build] fix several Makefile issues

- nil/internal/execution/state.go
- nil/internal/types/block.go
- nil/internal/types/serialization_test.go
- nil/services/cliservice/block.go
- nil/services/cliservice/block_format_test.go
- nil/services/rpc/jsonrpc/eth_block_test.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/synccommittee/prover/tracer/internal/mpttracer/mpt_tracer.go
The coinbase address is used at the execution layer to receive priority fees, and can be accessed via the `COINBASE` opcode from smart contracts.
Add the coinbase address to the block structure and the relevant RPC responses. Currently, the coinbase address is hardcoded as `0x0` for each shard and will require further adjustments in accordance with protocol.
Re-canonize tests to reflect the new block structure.
- Add coinbase to block and RPC response
- Re-canonize tests
> feat: add coinbase address to block structure and RPC
