- .github/workflows/build_artifacts.yml
- .github/workflows/main.yml
We need it to run on push to main, where it publishes new deb packages etc.
> Extract "Build artifacts" as a separate workflow

- nil/cmd/sync_committee_cli/internal/commands/batch_decode.go
- nil/cmd/sync_committee_cli/main.go
- nil/services/synccommittee/core/batches/blob/reader.go
- nil/services/synccommittee/core/batches/blob/reader_test.go
- nil/services/synccommittee/core/batches/encode/errors.go
- nil/services/synccommittee/core/batches/encode/header.go
- nil/services/synccommittee/core/batches/encode/v1/decoder.go
- nil/services/synccommittee/core/batches/encode/v1/zstd.go
- nil/services/synccommittee/internal/types/block_batch.go
debug utilities for decoding L1 blobs. Since we do not have agreement on how this decoded data are planned to be used - for now I am using `protojson proto.Batch` intermediate view as a human readable file content
> sync committee blob reader

- docs/nil/intro.mdx
Some links on the new index page of docs were broken. This diff fixes them.
> [docs] fixes to 500 links

- docs/docusaurus.config.js
- docs/src/css/custom.css
This diff attempts to fix incorrect CSS loading in docs.
> [docs] return of the switch

- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
We need to manually break consensus loop in case if it stucks for a some reason. Right now we do that in case if a syncer saved newer block than we run consensus on.
> [scheduler] break consensus loop on new block

- docs/src/components/CustomChatRuntimeProvider/index.tsx
- docs_ai_backend/app/api/chat/route.ts
This diff adds two important UI improvements for the docs bot:
* Adds an initial `Thinking...` state to indicate that the bot has received a request and is now processing it
* Restores proper text streaming so that the user sees the response right away
> [docs] ai improvements to support streaming

- nil/internal/network/dht.go
The validator still hogs the CPU during those 5 seconds, but this will be addressed separately.
> [network] Perform peer discovery only for 5 seconds per minute

- docs/nil/getting-started/gas-and-value.mdx
This diff adjusts the 'gas and value' tutorial to reflect the new fee model.
> [docs] added explanation of the new fee model

- docs/src/components/CustomChatRuntimeProvider/index.tsx
- docs_ai_backend/app/api/chat/route.ts
- docs_ai_backend/src/core/QueryHandler.ts
- nix/npmdeps.nix
- package-lock.json
This diff adjusts the AI prompt flow to clearly differentiate between generating TS/JS code and Solidity code. It also adds a timeout to the chat runtime so if ChatGPT is unavailable, we display a warning.
> [docs] adjusted prompts and added a timeout error

- docs_ai_backend/src/utils/populateDB.js
This diff fixes the incorrect path to installed smart-contracts in the AI backend.
> [docs] Update path to installed smart-contracts

- docs/src/components/CustomChatRuntimeProvider/index.tsx
- docs_ai_backend/app/api/chat/route.ts
- docs_ai_backend/src/core/QueryHandler.ts
This diff further adjusts AI prompts so that code generation works better.
> [docs] additional prompt refinement

- nil/tests/cli/cli_test.go
The first one is about testing CLI service from Go code. The second one checks that cli binary works fine.
The main motivation is improving performance because we start nil server for each test that is quite slow procedure.
> [tests] split cli tests into 2 independent groups

- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/execution/Makefile.inc
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/proposal.go
- nil/internal/execution/state.go
Splitting between internal and external incoming transactions.
Proposal will contain proofs for internal transactions in the future, but not, obviously, for external ones.
Also, put forwarded transactions before outgoing transactions generated in the block.
> Proposal refactoring

- nil/cmd/nil/common/args.go
- nil/go-ibft/README.md
- nil/services/synccommittee/prover/tracer/internal/mpttracer/mpt_tracer.go
- nil/services/synccommittee/prover/tracer/state_db.go
- amout → amount
- Backned → Backend
- commitedAcc → committedAcc
- copyOccured → copyOccurred
> Fix spelling errors

- clijs/README.md
- docs_ai_backend/README.md
- niljs/README.md
Updated incorrect `LICENSE` links in multiple `README.md` files to ensure consistency.  
No functional changes, just documentation fixes.
> [docs] Fix broken links in README files

- clijs/test/commands/smart-account/balance.test.ts
- docs/tests/cookbook-swap.test.mjs
- docs_interactive_tutorials_service/src/app/api/user/route.ts
- docs_interactive_tutorials_service/src/clients/DBClient.ts
- niljs/src/smart-accounts/SmartAccountV1/SmartAccountV1.ts
Use given feeCredit instead of estimated one in case of MaxFeePerGas estimation
Fix the problem with contract deployment. FeeCredits can be used from params
> Use given feeCredit instead of estimated one in case of MaxFeePerGas estimation

- docs_ai_backend/package.json
- nix/npmdeps.nix
- package-lock.json
This update is intended to fix the ansible error on nil-docs instance:
```
Feb 11 17:55:16 nil-docs provision.sh[152620]: fatal: [nil_docs]: FAILED! => {"changed": true, "cmd": "~/.nvm/nvm-exec npm ci\n", "delta": "0:00:05.132154", "end": "2025-02-11 17:55:16.722559", "msg": "non-zero return code", "rc": 1, "start": "2025-02-11 17:55:11.590405", "stderr": "npm ERR! code EUSAGE\nnpm ERR! \nnpm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.\nnpm ERR! \nnpm ERR! Missing: react@19.0.0 from lock file\nnpm ERR! Missing: react-dom@19.0.0 from lock file\nnpm ERR! Missing: scheduler@0.25.0 from lock file\nnpm ERR! \nnpm ERR! Clean install a project\nnpm ERR! …
```
> [docs-ai] Upgrade react version

- docs_ai_backend/package.json
- docs_interactive_tutorials_service/package.json
- nix/npmdeps.nix
- package-lock.json
This diff fixes the `npm ci` error in the `Build artifacts` workflow.
> [ci] npm ci fix

- nil/services/synccommittee/internal/metrics/task_storage_metrics.go
Rearranged set of attributes for task-related metrics for proper aggregation of values in SigNoz
> Sync Committee: Fixed task storage metrics

- nil/services/synccommittee/internal/types/errors.go
- nil/services/synccommittee/prover/internal/constants/proof_producer_codes.go
Alignment with proof-producer error code list: added support for managed OutOfMemory error
> add new proof producer error code

- nil/cmd/nil_block_generator/internal/commands/client.go
- nil/cmd/nil_block_generator/internal/commands/client_test.go
- nil/cmd/nil_block_generator/internal/commands/config.go
- nil/cmd/nil_block_generator/main.go
- nil/tests/rpc_suite.go
Added test for `nil_block_generator`:
- Init
- Deploy contract
- Generate block
> block_generator CLI:  Add unit test

- nil/internal/execution/block_generator.go
- nil/internal/execution/state.go
- nil/internal/execution/testaide.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/services/rpc/rawapi/local_call.go
Follow-up 44b36b686fc853d58c669c7c9a901d8031246626
> [execution] drop unused timer field from config

- flake.nix
- nix/npmdeps.nix
- nix/walletextension.nix
- package-lock.json
- wallet-extension/package.json
- wallet-extension/test/integration/faucet.test.ts
- wallet-extension/test/integration/helper.ts
- wallet-extension/test/integration/smartAccount.test.ts
- wallet-extension/test/testEnv.ts
- wallet-extension/test/vitest.integration.config.ts
- wallet-extension/tsconfig.app.json
This PR adds integration tests which are triggered on every PR to make sure that latest version of network or nil.js does not break wallet
> add integration tests in wallet extension

- go.mod
- go.sum
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/config/params.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/consensus/ibft/messages.go
- nil/internal/consensus/ibft/signer.go
- nil/internal/consensus/ibft/verifier.go
- nil/internal/crypto/bls/bls.go
- nil/internal/crypto/bls/common/interface.go
- nil/internal/crypto/bls/interface.go
- nil/internal/crypto/bls/kyber/aliases.go
- nil/internal/crypto/bls/kyber/bls.go
- nil/internal/crypto/bls/kyber/init.go
- nil/internal/crypto/bls/kyber/kyber_test.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/state.go
- nil/internal/keys/keys.go
- nil/internal/signer/block_verifier.go
- nil/internal/types/Makefile.inc
- nil/internal/types/block.go
- nil/internal/types/block_test.go
- nil/internal/types/signature.go
- nil/internal/types/ssz_test.go
- nil/services/nilservice/config.go
- nix/nil.nix
This patch introduces BLS signature scheme and it's implementation using kyber. The implementation is hiddent behind interfaces, so we will be able to replace it when the time comes.
> [consensus] introduce bls

- nil/client/direct_client.go
- nil/cmd/nild/devnet.go
- nil/common/logging/ch_logger.go
- nil/common/logging/fields.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/services/nilservice/config.go
- nil/services/nilservice/service.go
- nil/services/rpc/httpcfg/http_cfg.go
- nil/services/rpc/jsonrpc/eth_api.go
- nil/services/rpc/jsonrpc/eth_api_test.go
- nil/services/rpc/jsonrpc/send_transaction.go
- nil/services/rpc/server.go
- nil/services/rpc/transport/handler.go
- nil/services/rpc/transport/handler_test.go
- nil/services/rpc/transport/server.go
- nil/services/rpc/transport/server_test.go
- nil/services/rpc/transport/types.go
enable client event logging in RPC introduced in [recent commit](https://github.com/NilFoundation/nil/pull/302)
> enable events logging on RPC server

- README.md
- docs/nil/architecture/contract-co-location.mdx
- docs/nil/architecture/data-availability.mdx
- docs/nil/cookbook/english-auction/create-eng-auction.mdx
- docs/nil/cookbook/index.mdx
- docs/nil/cookbook/swap/create-swap-contract.mdx
- docs/nil/core-concepts/transaction-lifecycle.mdx
- docs/nil/fundamentals.mdx
- docs/nil/nil-101.mdx
- docs/nil/nild.mdx
- docs/nil/prerequisites.mdx
This diff fixes some annoying typos in several files. The revision was originally made by @samdotola.
> [docs] typos fix by @samdotola

- nil/services/synccommittee/core/service_test.go
- nil/services/synccommittee/internal/srv/service.go
- nil/services/synccommittee/internal/srv/service_test.go
Introduced a Stop method for the `srv.Service`, enabling externally triggered resource cleanup and worker termination. Updated tests to verify the new behavior, including worker start and stop processes.
> Sync Committee: Add graceful shutdown to `srv.Service`

- nil/services/synccommittee/core/proposer.go
- nil/services/synccommittee/internal/storage/block_storage.go
Modified the Proposer's initialization logic to prevent service termination in case of an L1 state root initialization error
> Sync Committee Proposer: State root initialization

- nil/internal/collate/proposer_test.go
- nil/internal/collate/replay_scheduler.go
- nil/internal/collate/scheduler.go
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/consensus/ibft/validators.go
- nil/internal/consensus/ibft/verifier.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/state.go
- nil/internal/types/block.go
- nil/internal/types/block_test.go
- nil/internal/types/ssz_test.go
Info about the previous validator will allow you to choose the next one more honestly.
> [types] extend block info with round and validator index

- nil/services/rollup/l1_fetcher.go
That's possible that proposer read current header value when at the same time fetcher updates it.
This patch fixes it.
Closes #372
> [rollup] fix data race in L1 fetcher

- create-nil-hardhat-project/package.json
- nix/npmdeps.nix
- package-lock.json
this updates version of the `create-nil-hardhat-project` package
> bump create-nil-hh-proj version

- explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
- explorer_frontend/src/features/contracts/components/Deploy/ShardIdInput.tsx
- explorer_frontend/src/features/contracts/init.ts
- explorer_frontend/src/features/shared/components/Token/index.tsx
This diff fixes several minor problems:
- Adds tokens names to account page
- Fixes issue with scroll to the top of deploy modal on "Deploy" button press
- Adds proper handling for the situation where shards amount can not be received by playground (disable validation and show warning)
> Fix playground deploy button scroll behavior

- CONTRIBUTION-GUIDE.md
This PR adds a Contribution Guide for the project which developers can go through for contributing to the project. The guide involves various steps for contributing and the procedures to follow for opening an Issue or PRs.
> Add contribution guide

- nil/common/sszx/map.go
- nil/internal/collate/proposer.go
- nil/internal/collate/proposer_test.go
- nil/internal/collate/validator.go
- nil/internal/consensus/ibft/ibft.go
- nil/internal/execution/Makefile.inc
- nil/internal/execution/execution_state_test.go
- nil/internal/execution/proposal.go
- nil/internal/execution/tries.go
- nil/internal/mpt/accessors.go
- nil/internal/mpt/mpt.go
- nil/internal/mpt/node.go
- nil/internal/mpt/proof.go
- nil/internal/mpt/proof_test.go
- nil/tests/economy/economy_test.go
https://github.com/NilFoundation/nil/issues/62
Fulfilling the requirement of internal txn proofs in the proposal.
> [proposal] Add parent block headers and txn proofs

- nil/internal/config/params.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/proposal.go
- nil/internal/types/block.go
- nil/internal/types/signature.go
- nil/internal/types/signature_test.go
- nil/internal/types/transaction.go
- nil/services/synccommittee/prover/tracer/tracer.go
- nil/tests/consensus/consensus_test.go
See details in commit messages. But basically this patchset removes unused code.
> [types] cleanup code a bit

- nil/internal/collate/validator.go
Before we did it only on InsertProposal step. But since syncer can interrupt consensus if new block inserted before consensus finished we need also remove processed messages also after ReplayBlock step.
Closes #405
> [collate] clean txpool messages on block replay

- nil/services/txnpool/txnpool.go
- nil/services/txnpool/txnpool_test.go
During replacement, take into account effective priority fee, not just feeCredit.
Closes #446
> Fix replacement in txpool

- nil/internal/consensus/ibft/metrics.go
- nil/internal/execution/metrics.go
This metrics should be gauges, not historgams.
> fix metrics types

- flake.lock
- nil/services/journald_forwarder/main.go
- nil/services/nilservice/service.go
- nix/nil.nix
Just regular update and fix of two new warnings.
> bump golangci-lint

- explorer_backend/package.json
- nix/npmdeps.nix
- package-lock.json
> Update niljs version in explorer_backend

- nil/internal/execution/account_state.go
- nil/tests/cli/cli_test.go
- nil/tests/multitoken/multitoken_test.go
> Remove tokens with zero balance from account

- nil/services/admin/server.go
- nil/services/admin/server_test.go
If the server was terminated ungracefully, an unused Unix socket file may remain on the filesystem. Upon restarting the process, this can lead to a failure with an "address already in use" error. Manually removing the socket file every time is inconvenient.
This patch introduces a check to ensure the socket is no longer in use and removes it if necessary.
As mentioned, reproducing this issue requires forcefully terminating the server, e.g., using `kill -9`, which makes it difficult to test.
> [admin] remove dangling Unix socket on admin server restart

- nil/go-ibft/core/ibft.go
This patch adds histograms for "new round", "commit" and "prepare" stages. There is also "fin" stage. But it seems to be empty.
> [go-ibft] add more metrics for specific stages

- nil/internal/collate/scheduler.go
Seems before it was a possible case when ticker channel could produce more messages than expected. That's why on our dev stand we saw quite strange behaviour when main shard ticked faster than others. This patch changes approach and now collation/sequence should start in a special time slot.
E.g. we have collationTickPeriod = 1s.
After this patch we will start consensus only at start of the next second. E.g. we stopped previous sequence at t = 1600ms so we don't start new sequence until 2000 (because t % 1000 == 0).
See #451
Before/after:
> [collate] start new sequence only in special time slot

- nil/cmd/relay/main.go
- nil/internal/cobrax/cmdflags/network.go
- nil/internal/network/config.go
- nil/internal/network/host.go
- nil/internal/network/relay_test.go
- nil/internal/network/testaide.go
Added network option to use a set of relays.
Added a test.
Added forcing private/public reachability for test purposes.
> [network] Use relay servers

- nil/services/synccommittee/internal/rpc/task_request_handler_rpc_suite_test.go
Locally, a parallel run in GoLand consistently fails this test
> [GH-#] Do not use real network in test

- nil/cmd/nil_load_generator/main.go
- nil/services/nil_load_generator/service.go
- nil/tests/nil_load_generator_service/nil_load_generator_test.go
We need to wait block ticks before deploy contracts in cluster.
> [loadgen] Waiting cluster to start up before execute operations

- Makefile
- go.mod
- go.sum
- nil/internal/collate/syncer.go
- nil/internal/collate/validator.go
- nil/internal/consensus/ibft/transport.go
- nil/internal/network/config.go
- nil/internal/network/connection_manager/config.go
- nil/internal/network/connection_manager/connection_manager.go
- nil/internal/network/connection_manager/notifiee.go
- nil/internal/network/connection_manager/peer_info.go
- nil/internal/network/connection_manager/peer_reputation_tracker.go
- nil/internal/network/connection_manager/reputation.go
- nil/internal/network/connection_manager/testaide.go
- nil/internal/network/host.go
- nil/internal/network/manager.go
- nil/internal/network/manager_test.go
- nil/internal/network/peer_reputation_tracker.go
- nil/internal/network/pubsub.go
- nil/internal/network/pubsub_test.go
- nil/services/txnpool/txnpool.go
- nix/nil.nix
> [GH-561] Connection manager

- explorer_frontend/src/features/shared/components/Sidebar/Navigation.tsx
- explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
This diff adjusts the index page of Explorer by adding an explicit link to interactive tutorials.
> [explorer] added link to tutorials from the index page of Explorer

- nil/services/admin/server.go
We need it to investigate possible pubsub issues.
> [admin] allow to set pprof options via admin socket

- docs/docusaurus.config.js
- docs/nil/migration-guides/march-1803-2025-release.mdx
- docs/sidebar-nil.js
This diff adds a migration guide for the 18.03.2025 release to docs.
> [docs] added migration guide for new release

- l1-contracts/package.json
- nix/npmdeps.nix
- package-lock.json
> pin hardhat

- explorer_frontend/src/features/tutorial-check/checks/tutorialFiveCheck.ts
- explorer_frontend/src/features/tutorial/spec.ts
- explorer_frontend/src/features/tutorial/tutorialImports.ts
- explorer_frontend/vite.config.ts
This diff adjusts imports for tutorials to remove unnecessary awaits.
> [explorer] adjusted imports for tutorials to avoid unnecessary awaits

- nil/cmd/relay/main.go
- nil/internal/network/config.go
- nil/internal/network/host.go
- nil/internal/telemetry/internal/resource.go
- nil/internal/telemetry/telemetry.go
Generating config for relay from relay cli.
Additionally, some improvements of cli commands
> [relay] Generate config

- nil/cmd/nil/internal/debug/debug.go
- nil/internal/execution/fee_test.go
- nil/services/rpc/rawapi/local_receipt.go
- nil/tests/cli/cli_test.go
Also, fix GasPrice calculation for receipts: take into account the priority fee.
> Refine output of `cli debug` command

- nix/npmdeps.nix
- nix/rollup-bridge-contracts.nix
- package-lock.json
- rollup-bridge-contracts/package.json
- add missing dependecies
- Reduce the bundle size
> Add missing Hardhat dependecies

- nil/services/stresser/core/helper.go
`WaitTx` was implemented in a way when sometimes it could fail with DestinationContractDoesNotExist error. That happened because we need to be sure that all messages in receipt is completed (not only top-level exteral message).
> [stresser] fix waiting for receipt on contract deploy

- nil/internal/telemetry/internal/config.go
- nil/internal/telemetry/internal/prometheus.go
- nil/internal/telemetry/internal/resource.go
- nil/internal/telemetry/telattr/attributes.go
- nil/internal/telemetry/telemetry.go
Prometheus metrics currently don't show the service name. Fixing it.
> [telemetry] Service name label in prometheus metrics

- nil/internal/execution/account_state.go
> [execution] Delete zero values from MPT storage instead of writing them

- nil/services/journald_forwarder/main.go
In case logs can't be handle successfully return error to otel contrib collector, so in this can he can try to send them later.
> [journald-forwarder] Check logs write success

- explorer_frontend/src/features/transaction/components/Logs.tsx
- explorer_frontend/src/features/transaction/components/Transaction.tsx
- explorer_frontend/src/features/transaction/components/assets/no-log.svg
- explorer_frontend/src/pages/transaction/TransactionPage.tsx
This PR re-applies the changes from https://github.com/NilFoundation/nil/pull/674, preserving the original commit authorship by @abdegenius
All commits have been GPG-signed to meet our contribution requirements
No changes were made to the code itself — just re-signing for compliance. 🙌
Closes https://github.com/NilFoundation/nil/issues/599
> Review/update txn UI

- docs/docusaurus.config.js
- docs/nil/nil-101.mdx
- docs/nil/nilcli/getting-started.mdx
- nil/cmd/nil/README.md
- scripts/install_cli.sh
currently we have a separate `nil_cli` repo which needs to be deprecated in favor of our main repo
> add CLI install script to main repo

- explorer_backend/daos/transactions.ts
This PR re-applies the changes from https://github.com/NilFoundation/nil/pull/651, preserving the original commit authorship by @ekumamatthew
All commits have been GPG-signed to meet our contribution requirements
No changes were made to the code itself — just re-signing for compliance. 🙌
Closes https://github.com/NilFoundation/nil/issues/566
> Review/feat:improve sql chronological tx sort

- nil/client/rpc/client.go
A small helper for the frequency pattern
> [GH-#] Code deduplication in the client

- nil/services/relayer/internal/l1/l1_bridge_messenger_abi.json
- nil/services/relayer/internal/l2/l2_bridge_messenger_abi.json
This PR includes only updates to compiled L1/L2 BridgeMessenger ABIs
> relayer: recompile l1/l2 ABI

- nil/client/client.go
- nil/client/direct_client.go
- nil/client/rpc/client.go
- nil/client/txpool_client.go
- nil/internal/types/transaction.go
- nil/services/nilservice/service.go
- nil/services/rpc/jsonrpc/send_transaction_test.go
- nil/services/rpc/jsonrpc/txpool_api.go
- nil/services/rpc/jsonrpc/txpool_api_test.go
- nil/services/rpc/jsonrpc/types.go
- nil/services/rpc/rawapi/api.go
- nil/services/rpc/rawapi/client.go
- nil/services/rpc/rawapi/local_txnpool.go
- nil/services/rpc/rawapi/node.go
- nil/services/rpc/rawapi/pb/conversion.go
- nil/services/rpc/rawapi/proto/transaction.proto
- nil/services/rpc/rawapi/server.go
- nil/services/synccommittee/internal/testaide/blocks.go
- nil/services/txnpool/txnpool.go
- nil/tests/rpc_service/rpc_service_test.go
> [txpool, api] Introduce txpool RPC API for txpool inspecting  

- nil/services/synccommittee/internal/executor/task_executor_test.go
Log was following:
```
nil> ==================
nil> WARNING: DATA RACE
nil> Write at 0x00c000360670 by goroutine 44:
nil>   github.com/NilFoundation/nil/nil/services/synccommittee/internal/executor.(*TestSuite).SetupTest()
nil>       /build/source/nil/services/synccommittee/internal/executor/task_executor_test.go:28 +0x2ef
nil>   github.com/stretchr/testify/suite.Run.func1()
nil>       /build/source/vendor/github.com/stretchr/testify/suite/suite.go:192 +0x30f
nil>   testing.tRunner()
nil>       /nix/store/g29rrn8qqlg4yjqv543ryrkimr7fk43h-go-1.24.1/share/go/src/testing/testing.go:1792 +0x225
nil>   testing.(*T).Run.gowrap1()
nil>       /nix/store/g29rrn8qqlg4yjqv543ryrkimr7fk43h-go-1.24.1/share/go/src/testing/testing.go:1851 +0x44
nil>
nil> Previous read at 0x00c000360670 by goroutine 43: …
```
> [test] fix race condition in Test_TaskExecutor_Busy_Handler

- nil/services/rpc/jsonrpc/send_transaction.go
- nil/services/rpc/transport/handler.go
This PR just make two logs more clear.
> [logs] Make served msg little bit more detailed and change Log type to Info

- nil/services/relayer/internal/l1/finality_ensurer.go
- nil/services/relayer/internal/l1/finality_ensurer_test.go
Fixed flaky test of the relayer finality ensurer
`started` signal had possibility to be emitted too early from the FinalityEnsurer component, before its subroutines have subscribed to the timer events. This led to loss of some events and eventual test freeze.
- Add additional started channels to each part of the ensurer
- Close them only after ticker is initialized
- Wait for all of them before signalling `started` to the test
https://github.com/NilFoundation/nil/issues/293#issuecomment-2771521616
> relayer fin ensurer: fix 'started' condition check

- Makefile
- flake.nix
rename cometa binary in nix outputs. this fixes https://github.com/NilFoundation/nil/pull/739
> fix cometa binary renaming

- nil/tests/regression/regression_test.go
- nix/tests-heavy.txt
- nix/tests-ibft.txt
Seems we had some issues in CI with consensus timeouts on big transactions.
> [tests] enable consensus for regression test suite

- docs/tests/working-with-smart-contracts-cli.test.mjs
- nil/cmd/nil/internal/block/block.go
- nil/cmd/nil/internal/block/params.go
- nil/cmd/nil/internal/cometa/command.go
- nil/cmd/nil/internal/cometa/params.go
- nil/cmd/nil/internal/contract/address.go
- nil/cmd/nil/internal/contract/call-readonly.go
- nil/cmd/nil/internal/contract/deploy.go
- nil/cmd/nil/internal/contract/estimate-fee.go
- nil/cmd/nil/internal/contract/params.go
- nil/cmd/nil/internal/contract/send-external-transaction.go
- nil/cmd/nil/internal/debug/debug.go
- nil/cmd/nil/internal/smartaccount/call-readonly.go
- nil/cmd/nil/internal/smartaccount/deploy.go
- nil/cmd/nil/internal/smartaccount/estimate-fee.go
- nil/cmd/nil/internal/smartaccount/new.go
- nil/cmd/nil/internal/smartaccount/params.go
- nil/cmd/nil/internal/smartaccount/send-tokens.go
- nil/cmd/nil/internal/smartaccount/send-transaction.go
> [GH-127] Give each command a separate parameter object

- nil/services/nil_load_generator/jsonrpc.go
- nil/services/nil_load_generator/service.go
In #689 we [changed](https://github.com/NilFoundation/nil/pull/689/files#diff-a18687f3a74a1cb1560f096d81591740be0aed4c88f56a370316bcb03234891bR17) signature of JSON-RPC method. This change should not have happened. It has been corrected in this PR.
> [GH-#] Load generator API recovery

- explorer_frontend/src/features/transaction/components/Overview.tsx
This PR adds some basic code for parsing the bytcode to Transaction Details.
This would be further revisited in another issue to integrate the `niljs` method for doing this
- Added a `Default` tab that is not displayed
#601 
Fixes #[Issue Number]  
or  
Related to #[601]
None
> Add basic code for Parsing Bytecode

- nil/internal/collate/proposer.go
- nil/internal/execution/block_generator.go
- nil/internal/execution/state.go
This patch fixes TxIdGap error that was caused by internal system messages from/to main shard. Here we assign manually that id for system transactions.
> [proposer] fix TxIdGap error on L1 contract tx

- clijs/src/base.ts
- clijs/src/common/config.test.ts
- clijs/src/common/config.ts
this fixes problem described in #742
> [GH-742] [cli.js] fallback for cometa and faucet endpoints in config

- clijs/src/commands/smart-account/balance.ts
- clijs/src/commands/smart-account/info.ts
- clijs/src/commands/smart-account/new.ts
this should fix problem with cli.js introduced in [one](https://github.com/NilFoundation/nil/pull/806) of recent PRs
> fix clijs test

- explorer_backend/daos/blocks.ts
- explorer_backend/daos/transactions.ts
- explorer_backend/validations/BlockSchema.ts
- explorer_backend/validations/TransactionSchema.ts
Fix issue with timestamp in database that we do not actually use and it's removed
Remove timestamp + fix scheme
> [explorere_backend] remove timestamp usage from db queries

- explorer_backend/daos/transactions.ts
Still have typo that lead to some queries of transactions were incorrect.
> [explorer] Fix dao issue with query

- clijs/.oclifrc.json
- clijs/package.json
- clijs/src/commands/util/index.ts
- clijs/src/commands/util/list-commands.ts
- clijs/src/sea.ts
- nix/clijs.nix
ppl often forget to add new clijs command to the sea.ts file. this leads to absence of these command in the final package. here is simple test for the case added
> check bundled clijs integrity

- hardhat-plugin/package.json
- hardhat-plugin/rollup/rollup.config.mjs
- hardhat-plugin/src/config.d.ts
- hardhat-plugin/src/index.ts
- hardhat-plugin/src/internal/contracts.ts
- hardhat-plugin/src/tasks/subtasks.ts
- hardhat-plugin/src/types.ts
- hardhat-plugin/tsconfig.json
- niljs/src/contract-factory/ContractFactory.ts
- nix/npmdeps.nix
- nix/uniswap.nix
- pnpm-lock.yaml
- uniswap/hardhat.config.ts
- uniswap/package.json
- uniswap/tasks/token/info.ts
- uniswap/tsconfig.json
In this PR I add getContractAt that work from Hardhat.
> [hardhat] Hardhat getContractAt

- explorer_frontend/src/features/search/components/Search.tsx
- explorer_frontend/src/features/shared/components/InternalPageContainer.tsx
- explorer_frontend/src/features/shared/components/Layout/Navbar.tsx
- explorer_frontend/src/features/shared/components/Layout/styles.ts
- explorer_frontend/src/features/shared/components/MobileConvertableTable.tsx
- explorer_frontend/src/features/transaction-list/components/TransactionList.tsx
- explorer_frontend/src/features/transaction/components/Logs.tsx
- explorer_frontend/src/pages/address/AddressPage.tsx
- explorer_frontend/src/pages/block/BlockPage.tsx
- explorer_frontend/src/pages/explorer/ExplorerPage.tsx
- explorer_frontend/src/pages/explorer/styles.ts
- explorer_frontend/src/pages/transaction/TransactionPage.tsx
- explorer_frontend/src/styleHelpers.ts
- Closes: #624 
- Applied resizing logic to main Explorer page
- Applied new resizing logic to Transaction page as well 
- Transaction table on Block Page scrolls horizontally in tablet view
> Feat: Applied new Explorer resizing logic

- explorer_frontend/tests/tutorials/tutorials.test.mts
That's updating for test in explorer.
> [explorer] fix tests import

- .gitignore
- Makefile
- explorer_frontend/src/features/tutorial-check/checks/tutorialFiveCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialFourCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialOneCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialThreeCheck.ts
- explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
- nil/contracts/solidity/tests/TokensTest.sol
Previously, it was generated in the `lib` folder. However, since this folder is shared with the `smart-contracts` component, it can lead to potential issues.
> [contracts] Move `console.sol` to system folder

- .github/workflows/publish_npm.yml
- create-nil-hardhat-project/package.json
- hardhat-plugin/package.json
Hardhat Plugin: prepare and publish
- [v] I have read and followed the [Contributing Guide](https://github.com/NilFoundation/nil/blob/main/CONTRIBUTION-GUIDE.md)
- [v] I have tested the changes locally
- [v] I have added relevant tests (if applicable)
- [v] I have updated documentation/comments (if applicable)
> Hardhat Plugin: prepare and publish

- scripts/publish_npm_packages.sh
Fix publish script to publish hardhat plugin
- [v] I have read and followed the [Contributing Guide](https://github.com/NilFoundation/nil/blob/main/CONTRIBUTION-GUIDE.md)
- [v] I have tested the changes locally
- [v] I have added relevant tests (if applicable)
- [v] I have updated documentation/comments (if applicable)
> hardhat plugin: publish (fix)

- uniswap/README.md
hey team! I found duplicate words and fixed them.
> docs: remove consecutive duplicate words

- rollup-bridge-contracts/contracts/bridge/l2/L2BridgeMessenger.sol
- rollup-bridge-contracts/contracts/bridge/l2/interfaces/IL2BridgeMessenger.sol
- rollup-bridge-contracts/contracts/common/NilMessageTree.sol
- rollup-bridge-contracts/contracts/interfaces/INilMessageTree.sol
view function for NilMessageTree and L2BridgeMessenger  for merkleRoot
> feat: view function for NilMessageTree and L2BridgeMessenger  for merkleRoot

- nil/services/synccommittee/Makefile.inc
- nil/services/synccommittee/core/config.go
- nil/services/synccommittee/core/feeupdater/contract_wrapper.go
- nil/services/synccommittee/core/feeupdater/updater_test.go
- nil/services/synccommittee/core/proposer_test.go
- nil/services/synccommittee/core/rollupcontract/eth_client.go
- nil/services/synccommittee/core/rollupcontract/generate.go
- nil/services/synccommittee/core/rollupcontract/wrapper.go
- nil/services/synccommittee/core/rollupcontract/wrapper_test.go
- nil/services/synccommittee/core/service.go
- nil/services/synccommittee/core/service_test.go
- nil/services/synccommittee/internal/l1client/eth_client.go
- rollup-bridge-contracts/contracts/bridge/l1/interfaces/IFeeStorage.sol
Added ABI integration with IFeeStorage contract from rollup-bridge-contracts
> sc fee updater: integrate with L1 contract

- nix/clijs.nix
No longer needed after solving #250
> [GH-#] Do not suppress node warnings in clijs tests

- explorer_frontend/src/features/shared/components/Layout/styles.ts
- explorer_frontend/src/pages/playground/PlaygroundPage.tsx
This diff fixes playground layout inconsistencies.
> fix: fix playground layout

- explorer_frontend/src/features/code/Code.tsx
- explorer_frontend/src/features/code/code-toolbar/ResourcesButton.tsx
- explorer_frontend/src/features/contracts/components/ContractsContainer.tsx
- explorer_frontend/src/features/logs/components/Logs.tsx
This diff fixes UI bugs in playground web version mentioned in #924
> fix: fix playground ui web version bugs

- rollup-bridge-contracts/scripts/bridge-test/bridge-eth-impl.ts
- rollup-bridge-contracts/scripts/bridge-test/bridge-eth.ts
- rollup-bridge-contracts/scripts/bridge-test/depost-withdrawal-loop.ts
- rollup-bridge-contracts/scripts/bridge-test/get-messenger-events.ts
- rollup-bridge-contracts/scripts/wallet/create-wallet-with-funding.ts
- rollup-bridge-contracts/task/fetch-relayeraddress-from-relayer.ts
- rollup-bridge-contracts/task/nil-smart-account.ts
- rollup-bridge-contracts/task/validate-l2-eth-bridging.ts
- rollup-bridge-contracts/test_integration.sh
This PR contains improvements and refactorings of current bridge testing scripts in order to support nildev bridge data loader
- bridgeETH function and its surroundings were upgraded for custom L1 & L2 account support
- depositAndWithdrawLoop script implemented in the deposit part: for now it just endlessly forwards money L1 --> L2
> nildev bridge test: deposit loop

- rollup-bridge-contracts/contracts/bridge/l2/L2ETHBridgeVault.sol
- rollup-bridge-contracts/scripts/bridge-test/depost-withdrawal-loop.ts
- rollup-bridge-contracts/scripts/bridge-test/withdraw-eth.ts
- rollup-bridge-contracts/task/generate-nil-smart-account.ts
- rollup-bridge-contracts/task/nil-smart-account.ts
- rollup-bridge-contracts/task/validate-l2-eth-bridging.ts
- Fixed L2ETHBridgeVault call
- Added Typescript file for calling withdrawal method
- Added withdrawal call to deposit-withdrawal loop
> withdraw e2e test prep

- nil/services/relayer/internal/debug/debug.go
- nil/services/relayer/internal/debug/heartbeat.go
- nil/services/relayer/internal/debug/metrics/metrics.go
- nil/services/relayer/service.go
Adding a simple heartbeat metric to the relayer service
> relayer heartbeat

- .github/workflows/build_artifacts.yml
https://github.com/NilFoundation/nil/actions/runs/15753326237/workflow
> [GH-#] Unexpected value 'environment' fixed

- Makefile
- nil/internal/execution/state.go
- nil/internal/serialization/containers.go
Tiny improvements. Extracted from other PRs so as not to crowd them.
Commented in code.
> Code cleanup
